import test from 'node:test';
import assert from 'node:assert/strict';
import {routeContact,settings,validate,CONTACT_API} from '../src/odyssey-contact.mjs';
const valid=()=>({name:'A visitor',email:'visitor@example.org',role:'playtesting',message:'I would like to help.',consent:true,token:'one-time-token',website:''});
const request=(body=valid(),extra={})=>new Request('https://kliawota.design'+CONTACT_API,{method:'POST',headers:{origin:'https://kliawota.design','content-type':'application/json',...extra},body:JSON.stringify(body)});
function setup(){const sent=[],checked=[];const env={ODYSSEY_CONTACT_ENABLED:'true',ODYSSEY_CONTACT_TO:'owner@example.com',ODYSSEY_TURNSTILE_SITEKEY:'public-example-sitekey',ODYSSEY_TURNSTILE_SECRET:'private-example-secret',ODYSSEY_EMAIL:{send:async m=>{sent.push(m);return{messageId:'accepted-id'};}}};const verify=async(url,opt)=>{checked.push({url,opt});assert.equal(url,'https://challenges.cloudflare.com/turnstile/v0/siteverify');return Response.json({success:true,hostname:'kliawota.design',action:'odyssey-interest'});};return {env,sent,checked,verify};}
test('missing configuration keeps the current email link usable',async()=>{const r=await routeContact(new Request('https://kliawota.design'+CONTACT_API),{});assert.deepEqual(await r.json(),{enabled:false});assert.equal((await routeContact(request(),{})).status,503);});
test('public config exposes only the sitekey, never addresses or secrets',async()=>{const {env}=setup();const v=await(await routeContact(new Request('https://kliawota.design'+CONTACT_API),env)).json();assert.deepEqual(v,{enabled:true,sitekey:'public-example-sitekey'});assert(!JSON.stringify(v).includes('private'));assert.equal(settings({...env,ODYSSEY_CONTACT_FROM:'spoof@example.com'}).enabled,false);});
test('send stays fixed to owner, supports reply-to, and returns only accepted status',async()=>{const h=setup(),r=await routeContact(request(),h.env,h.verify);assert.equal(r.status,202);assert.equal((await r.json()).submitted,true);assert.equal(h.sent.length,1);const m=h.sent[0];assert.equal(m.to,'owner@example.com');assert.equal(m.replyTo,'visitor@example.org');assert.equal(m.from.email,'UniverseEternal@kliawota.design');assert.equal(m.html,undefined);assert.match(m.text,/explicitly confirmed/);assert.match(m.subject,/Playtest/);});
for(const code of ['missing','origin','host','action','expired'])test('rejects '+code+' challenge or request without sending',async()=>{const h=setup();let req=request(),verify=h.verify;if(code==='missing')req=request({...valid(),token:''});else if(code==='origin')req=request(valid(),{origin:'https://attacker.example'});else verify=async()=>Response.json({success:code!=='expired',hostname:code==='host'?'attacker.example':'kliawota.design',action:code==='action'?'other':'odyssey-interest'});const r=await routeContact(req,h.env,verify);assert(r.status>=400);assert.equal(h.sent.length,0);});
for(const [name,changes]of Object.entries({injection:{email:'a@example.org\r\nBcc: bad@example.com'},recipient:{to:'bad@example.com'},noConsent:{consent:false},longName:{name:'x'.repeat(81)},longText:{message:'x'.repeat(2001)},honeypot:{website:'spam'},longToken:{token:'x'.repeat(2049)},invalidRole:{role:'__proto__'}}))test('rejects '+name,()=>assert.throws(()=>validate({...valid(),...changes})));
test('request size is enforced while reading, without trusting Content-Length',async()=>{const h=setup(),r=await routeContact(request({...valid(),message:'x'.repeat(13000)}),h.env,h.verify);assert.equal(r.status,400);assert.equal(h.checked.length,0);});
test('provider failure never returns success or leaks private details',async()=>{const h=setup();h.env.ODYSSEY_EMAIL.send=async()=>{throw Error('private account data');};const r=await routeContact(request(),h.env,h.verify),v=await r.json();assert.equal(r.status,502);assert(!v.submitted);assert(!JSON.stringify(v).includes('private account'));});
test('unavailable verification fails closed',async()=>{const h=setup(),r=await routeContact(request(),h.env,async()=>{throw Error('offline');});assert.equal(r.status,503);assert.equal(h.sent.length,0);});
test('unrelated paths are untouched and unsupported methods rejected',async()=>{assert.equal(await routeContact(new Request('https://kliawota.design/'),{}),null);assert.equal((await routeContact(new Request('https://kliawota.design'+CONTACT_API,{method:'DELETE'}),{})).status,405);});
