'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const sync=require('../public/mtgtools/odyssey/live-sheet-sync.js');
require('../public/mtgtools/odyssey/live-sheet-art-patch.js');
const root=path.resolve(__dirname,'..');
function baseline(){
 const cards=Array.from({length:309},(_,i)=>({id:'ODY-'+String(i+1).padStart(3,'0'),number:i+1,backFace:i===228?{imageUrl:'wooden-horse.jpg'}:undefined}));
 return {schema:'odyssey-studio-data/v1',datasetVersion:'old',cards,artworks:[],coverage:[],integrity:{},candidate:{}};
}
test('live sheet sync promotes the full current 309 and 604-art library',()=>{
 const d=sync.apply(baseline());
 assert.equal(d.datasetVersion,'2026-09-26.17');
 assert.equal(d.cards.length,309);assert.equal(d.artworks.length,604);assert.equal(d.coverage.length,309);
 assert.equal(new Set(d.cards.map(c=>c.number)).size,309);assert.equal(new Set(d.artworks.map(a=>a.id)).size,604);
 assert.equal(d.sheetSync.cardSheet.revision,'254');assert.equal(d.sheetSync.artSheet.revision,'101');
 const art=new Set(d.artworks.map(a=>a.id));const assigned=d.cards.filter(c=>c.primaryArt);
 assert.equal(assigned.length,309);for(const c of assigned)assert.ok(art.has(c.primaryArt),c.id+' has current art');
 assert.deepEqual(d.cards.filter(c=>!c.primaryArt).map(c=>c.number),[]);
});
test('current special layouts survive the sheet cutover',()=>{
 const d=sync.apply(baseline()),count=k=>d.cards.filter(c=>c.layout===k).length;
 assert.deepEqual({standard:count('standard'),saga:count('saga'),adventure:count('adventure'),prepare:count('prepare'),battle:count('battle'),vehicle:count('vehicle'),transform:count('transform')},{standard:275,saga:16,adventure:7,prepare:1,battle:0,vehicle:9,transform:1});
 for(const n of [208,209,222]){const c=d.cards.find(x=>x.number===n);assert.match(c.type,/Enchantment Creature.*Saga/i);assert.equal(c.layout,'saga');}
 const t=d.cards.find(c=>c.number===229);assert.equal(t.layout,'transform');assert.equal(t.backFace.imageUrl,'wooden-horse.jpg');
});
test('the newest artwork wave is directly renderable and assigned',()=>{
 const d=sync.apply(baseline()),fresh=d.artworks.filter(a=>+a.id.slice(4)>553);
 assert.equal(fresh.length,51);assert.ok(fresh.every(a=>/^https:\/\//.test(a.imageUrl)),fresh.filter(a=>!a.imageUrl).map(a=>a.id).join(','));
 assert.equal(d.cards.find(c=>c.number===84).primaryArt,'ART-582');
 assert.match(d.artworks.find(a=>a.id==='ART-582').credit,/Marie-Lan Nguyen.*CC BY 2.5/);
 assert.equal(d.cards.find(c=>c.number===84).primaryArt,'ART-582');
 assert.match(d.artworks.find(a=>a.id==='ART-582').credit,/Marie-Lan Nguyen.*CC BY 2.5/);
 assert.equal(d.cards.find(c=>c.number===4).primaryArt,'ART-244');
 assert.equal(d.cards.find(c=>c.number===6).primaryArt,'ART-236');
 assert.equal(d.cards.find(c=>c.number===12).primaryArt,'ART-578');
 assert.equal(d.cards.find(c=>c.number===245).primaryArt,'ART-574');
 assert.deepEqual([102,152,208,209,236].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-584','ART-027','ART-237','ART-020','ART-583']);
 assert.deepEqual([131,135,210,276].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-201','ART-585','ART-511','ART-517']);
 assert.deepEqual([130,259,262,263,266].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-275','ART-589','ART-588','ART-586','ART-587']);
 assert.deepEqual([59,148,191,194,214,216,226,265,280,288].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-155','ART-551','ART-219','ART-509','ART-540','ART-007','ART-019','ART-256','ART-510','ART-500']);
 assert.deepEqual([25,42,44,88,92,133,134,145,241,254,270].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-336','ART-387','ART-176','ART-187','ART-214','ART-316','ART-215','ART-323','ART-083','ART-287','ART-455']);
 const useCounts={};for(const c of d.cards)useCounts[c.primaryArt]=(useCounts[c.primaryArt]||0)+1;
 assert.equal(Object.values(useCounts).reduce((sum,n)=>sum+Math.max(0,n-1),0),0);
 assert.deepEqual([49,51,57,82,164,171,182,203,224,230,239,246].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-072','ART-594','ART-595','ART-599','ART-596','ART-523','ART-231','ART-026','ART-597','ART-598','ART-253','ART-105']);
 assert.deepEqual(['ART-594','ART-595','ART-596','ART-597','ART-598','ART-599'].map(id=>{const a=d.artworks.find(x=>x.id===id);return [a.id,a.imageWidth,a.imageHeight]}),[['ART-594',1920,1574],['ART-595',3804,2542],['ART-596',2000,1371],['ART-597',6488,4942],['ART-598',2080,1390],['ART-599',1920,1446]]);
 assert.equal(d.cards.find(c=>c.number===304).primaryArt,'ART-600');
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-600');return [a.imageUrl,a.imageWidth,a.imageHeight]})(),['https://kliawota.design/mtgtools/odyssey/art-telegonus-circe-roscher.jpg',1548,864]);
 assert.equal(d.cards.find(c=>c.number===10).primaryArt,'ART-601');
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-601');return [a.imageUrl,a.imageWidth,a.imageHeight,a.source]})(),['https://kliawota.design/mtgtools/odyssey/art-telemachus-assembly-calbet.jpg',2000,1360,'https://www.gutenberg.org/files/52927/52927-h/52927-h.htm']);
 assert.equal(d.cards.find(c=>c.number===56).primaryArt,'ART-430');
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-430');return [a.imageUrl,a.imageWidth,a.imageHeight]})(),['https://kliawota.design/mtgtools/odyssey/art-antinous-footstool-pogany.png',2160,1440]);
 assert.equal(d.cards.find(c=>c.number===302).primaryArt,'ART-602');
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-602');return [a.imageUrl,a.imageWidth,a.imageHeight,a.source]})(),['https://kliawota.design/mtgtools/odyssey/art-work-family-estate-steinhausen.jpg',2064,1260,'https://sammlung.staedelmuseum.de/en/work/worker-on-the-vineyard-1']);
 assert.deepEqual([33,75,305].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-138','ART-603','ART-604']);
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-603');return [a.imageUrl,a.imageWidth,a.imageHeight,a.source]})(),['https://kliawota.design/mtgtools/odyssey/art-mooring-rope-streatfeild.jpg',1920,1478,'https://commons.wikimedia.org/wiki/File:Deck_scene_with_three_men_hauling_on_a_rope_RMG_PZ4301.tiff']);
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-604');return [a.imageUrl,a.imageWidth,a.imageHeight,a.source]})(),['https://kliawota.design/mtgtools/odyssey/art-telegonus-wounds-ulysses-royal20di.jpg',2048,1105,'https://picryl.com/media/telegonus-and-ulysses-from-bl-royal-20-d-i-f-190-8ec866']);
 assert.deepEqual([33,75,305].map(n=>d.coverage.find(c=>c.number===n).status),['COVERED','COVERED','COVERED']);
 assert.deepEqual([56,302].map(n=>d.coverage.find(c=>c.number===n).status),['SELECTED','SELECTED']);
 assert.deepEqual([10,58].map(n=>d.coverage.find(c=>c.number===n).status),['SELECTED','SELECTED']);
 assert.deepEqual([173,178,304].map(n=>d.coverage.find(c=>c.number===n).status),['SELECTED','SELECTED','SELECTED']);
 assert.deepEqual([8,18,32,77].map(n=>d.coverage.find(c=>c.number===n).status),['SELECTED','SELECTED','SELECTED','SELECTED']);
 assert.equal(d.coverage.find(c=>c.number===231).status,'REVIEW');
 assert.match(d.coverage.find(c=>c.number===231).notes,/ART-181 is not Agamemnon/);
 assert.match(d.artworks.find(a=>a.id==='ART-181').subjects,/Elpenor/);
 assert.doesNotMatch(d.artworks.find(a=>a.id==='ART-181').subjects,/Agamemnon/);
 assert.deepEqual([24,31,37,66,82].map(n=>d.coverage.find(c=>c.number===n).status),['COVERED','COVERED','COVERED','COVERED','COVERED']);
 assert.deepEqual([60,83,126,244,261,281,306].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-122','ART-590','ART-592','ART-593','ART-545','ART-591','ART-104']);
 assert.deepEqual(['ART-590','ART-591','ART-592','ART-593'].map(id=>{const a=d.artworks.find(x=>x.id===id);return [a.id,a.imageWidth,a.imageHeight]}),[['ART-590',2911,3880],['ART-591',3888,5184],['ART-592',4874,5125],['ART-593',2427,4000]]);
 assert.deepEqual([96,99,113,137,196,242,257].map(n=>d.cards.find(c=>c.number===n).primaryArt),['ART-368','ART-512','ART-264','ART-526','ART-071','ART-318','ART-074']);
 assert.equal(d.coverage.every(c=>c.name===d.cards.find(card=>card.number===c.number).name),true);
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-155');return [a.imageWidth,a.imageHeight,a.rights]})(),[4000,2911,'Public Domain / NGA Open Access; Commons CC0']);
 assert.equal(d.cards.find(c=>c.number===130).name,"Nymph of Laertes' Orchard");
 assert.equal(d.cards.find(c=>c.number===309).name,'Zeus, Guardian of Strangers');
 assert.equal(d.coverage.find(c=>c.number===309).name,'Zeus, Guardian of Strangers');
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-201');return [a.imageWidth,a.imageHeight]})(),[793,1200]);
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-585');return [a.imageWidth,a.imageHeight]})(),[5231,3648]);
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-589');return [a.imageWidth,a.imageHeight]})(),[1024,840]);
 assert.deepEqual(['ART-583','ART-584'].map(id=>{const a=d.artworks.find(x=>x.id===id);return [a.id,a.imageWidth,a.imageHeight]}),[['ART-583',6382,4832],['ART-584',2560,1920]]);
 assert.deepEqual((()=>{const a=d.artworks.find(x=>x.id==='ART-020');return [a.imageUrl,a.imageWidth,a.imageHeight]})(),['https://iiif.micr.io/PmgVy/full/max/0/default.jpg',4102,2717]);
 assert.equal(d.coverage.find(c=>c.number===236).name,'The Burning Olive Stake');
});
test('Studio loads the sheet sync before model construction and links the current card source',()=>{
 const app=fs.readFileSync(path.join(root,'public/mtgtools/odyssey/app.html'),'utf8');
 const data=app.indexOf('odyssey-data.js?v=20260927-flavor1'),syncPos=app.indexOf('live-sheet-sync.js?v=20260927-art21'),patchPos=app.indexOf('live-sheet-art-patch.js?v=20260927-art21'),model=app.indexOf('const ODYSSEY_DATASET=loadOdysseyDataset()');
 assert.ok(data>=0&&syncPos>data&&patchPos>syncPos&&model>patchPos);
 assert.match(app,/ART-430\.1cce9d409251\.full\.webp/);
 assert.match(app,/function stalePackagedArtOverride/);
 assert.match(app,/cropProfileReset/);
 assert.match(app,/1-OTRpW8vrSJWcXcL06l3eMJESwFtt6hQqCEl9J3sdEE\/edit/);
 const index=fs.readFileSync(path.join(root,'public/mtgtools/odyssey/index.html'),'utf8');assert.match(index,/app\.html\?v=20260927-flavor1-art24/);
});
