import test from 'node:test';import assert from 'node:assert/strict';
import {subscriberWorkspace,routeSubscriptions,validateSignup,SIGNUP_API,CONSENT_VERSION,TOPICS,HEADERS,OWNER,SUBSCRIBER_SHEET,cleanupSubscriptions,csvCell} from '../src/odyssey-subscriptions.mjs';
import {MemoryStorage} from './subscription-storage.mjs';
const BASE='https://kliawota.design',IP='192.0.2.20';
const valid={email:'art-lover@example.org',name:'Test Person',topics:TOPICS,consent:true,consentVersion:CONSENT_VERSION,website:'',challenge:''};
function req(path='',body=null,extra={}){return new Request(BASE+SIGNUP_API+path,{method:body===null?'GET':'POST',headers:{Origin:BASE,'Content-Type':'application/json','CF-Connecting-IP':IP,...extra},...(body!==null?{body:JSON.stringify(body)}:{})});}
async function harness(){const storage=new MemoryStorage();let now=Date.parse('2026-09-29T06:00:00Z'),owner=OWNER,verified=true,googleFailure=false,writeMismatch=false,sheetRows=[HEADERS],googleCalls=[];
 const fetcher=async(url,opt={})=>{googleCalls.push({url,options:opt});if(url.includes('/userinfo'))return Response.json({email:owner,email_verified:verified});if(!url.startsWith('https://sheets.googleapis.com/v4/spreadsheets/'+SUBSCRIBER_SHEET))throw Error('Unexpected external service');if(googleFailure)return Response.json({},{status:403});if(url.includes('?fields='))return Response.json({sheets:[{properties:{sheetId:29430513,title:'Subscribers',gridProperties:{rowCount:10000,columnCount:13}}}]});if(url.endsWith('/values:batchUpdate')){const b=JSON.parse(opt.body);assert.equal(b.valueInputOption,'RAW');assert.equal(b.data.length,1);assert(b.data[0].range.startsWith("'Subscribers'!A1:M"));sheetRows=b.data[0].values;return Response.json({});}if(url.endsWith(':clear'))return Response.json({});return Response.json({values:writeMismatch?[['bad readback']]:sheetRows});};
 const call=(r)=>subscriberWorkspace(r,storage,fetcher,()=>now);
 async function challenge(){const r=await call(req('/challenge')),b=await r.json();const cookie=r.headers.get('Set-Cookie').split(';')[0];now+=1100;return{b,cookie};}
 async function signup(email=valid.email,extra={}){const {b,cookie}=await challenge();return call(req('',{...valid,email,challenge:b.challenge,...extra},{Cookie:cookie}));}
 return{storage,call,challenge,signup,advance:n=>now+=n,clock:()=>now,admin:(body)=>call(req('/admin',body,{Authorization:'Bearer test-google-access'})),notOwner:()=>owner='another@example.org',notVerified:()=>verified=false,googleCalls,failGoogle:()=>googleFailure=true,badReadback:()=>writeMismatch=true,sheet:()=>sheetRows};
}
test('normalizes a consenting single-opt-in request',()=>{const out=validateSignup({...valid,email:'  ART@example.org ',name:'  Reader  '});assert.equal(out.email,'art@example.org');assert.equal(out.name,'Reader');assert.deepEqual(out.topics,TOPICS);});
for(const [name,extra]of Object.entries({email:{email:'bad'},headers:{email:'a@example.org\r\nBcc:bad'},name:{name:'A\nB'},consent:{consent:false},version:{consentVersion:'v0'},noTopics:{topics:[]},unknownTopic:{topics:['secret']},duplicate:{topics:['progress','progress']},hidden:{website:'bot'},extra:{destination:'evil@example.org'}}))test('rejects '+name,()=>assert.throws(()=>validateSignup({...valid,...extra})));
test('public configuration contains no emails or rows and never calls Google',async()=>{const h=await harness(),r=await h.call(req()),v=await r.json();assert(v.enabled);assert.equal(v.verification,'single-opt-in');assert(!JSON.stringify(v).includes('@'));assert.equal(h.googleCalls.length,0);});
test('saved signup is durable, consented, unverified, and never sends email',async()=>{const h=await harness();assert.equal((await h.signup()).status,202);const rows=await h.storage.list({prefix:'member:'});assert.equal(rows.size,1);const row=[...rows.values()][0];assert.equal(row.email,valid.email);assert.equal(row.emailVerified,false);assert.equal(row.consentVersion,CONSENT_VERSION);assert.equal(row.status,'active');assert.equal(h.googleCalls.length,0);assert(!JSON.stringify([...h.storage.map]).includes(IP));const restarted=new MemoryStorage([...h.storage.map]);assert.equal((await restarted.list({prefix:'member:'})).size,1);});
test('duplicate normalized signup preserves previous preferences',async()=>{const h=await harness();await h.signup();await h.signup('ART-LOVER@example.org',{topics:['progress']});const rows=await h.storage.list({prefix:'member:'});assert.equal(rows.size,1);assert.deepEqual([...rows.values()][0].topics,TOPICS);});
test('challenge is cookie-bound, origin-bound, time-bound and replay-idempotent',async()=>{const h=await harness(),{b,cookie}=await h.challenge(),body={...valid,challenge:b.challenge};assert.equal((await h.call(req('',body))).status,403);assert.equal((await h.call(req('',body,{Cookie:cookie,Origin:'https://wrong.example'}))).status,403);assert.equal((await h.call(req('',body,{Cookie:cookie,'CF-Connecting-IP':'192.0.2.33'}))).status,403);assert.equal((await h.call(req('',body,{Cookie:cookie}))).status,202);assert.equal((await h.call(req('',body,{Cookie:cookie}))).status,202);assert.equal((await h.storage.list({prefix:'member:'})).size,1);h.advance(1200001);assert.equal((await h.call(req('',body,{Cookie:cookie}))).status,403);});
test('rate limits bound verified submissions and cleanup removes only old abuse keys',async()=>{const h=await harness();for(let i=0;i<5;i++)assert.equal((await h.signup('person'+i+'@example.org')).status,202);assert.equal((await h.signup('limit@example.org')).status,429);h.advance(3*86400000);await cleanupSubscriptions(h.storage,h.clock());assert.equal((await h.storage.list({prefix:'member:'})).size,5);assert.equal((await h.storage.list({prefix:'used:'})).size,0);assert.equal((await h.storage.list({prefix:'rate:'})).size,0);});
test('owner list is private and never served on a public GET',async()=>{const h=await harness();await h.signup();assert.equal((await h.call(req('/admin'))).status,405);assert.equal((await h.call(req('/admin',{action:'list'}))).status,403);h.notOwner();assert.equal((await h.admin({action:'list'})).status,403);const h2=await harness();h2.notVerified();assert.equal((await h2.admin({action:'list'})).status,403);});
test('CSV includes consent and functional unsubscribe; only active rows exported',async()=>{const h=await harness();await h.signup();await h.signup('second@example.org');let csv=await(await h.admin({action:'csv'})).text();assert(csv.includes('Email verified'));assert(csv.includes('"NO"'));const token=csv.match(/manage\.html#([a-f0-9]{64}\.[a-f0-9]{64})/)[1];assert.equal((await h.call(req('/unsubscribe?token='+token))).status,405);assert.equal((await h.call(req('/unsubscribe',{token}))).status,200);csv=await(await h.admin({action:'csv'})).text();assert.equal(csv.split('\r\n').length,2);const list=await(await h.admin({action:'list'})).json();assert.equal(list.active,1);assert.equal(list.total,2);const optOut=list.rows.find(x=>x.status==='unsubscribed');await h.signup(optOut.email);assert.equal((await(await h.admin({action:'list'})).json()).active,1);});
test('unsubscribe requires authentic token and never updates on link GET',async()=>{const h=await harness();await h.signup();assert.equal((await h.call(req('/unsubscribe',{token:'0'.repeat(64)+'.'+'0'.repeat(64)}))).status,403);assert.equal((await(await h.admin({action:'list'})).json()).active,1);});
test('delete removes PII and retains suppression without unintended resubscribe',async()=>{const h=await harness();await h.signup();const row=(await(await h.admin({action:'list'})).json()).rows[0];assert.equal((await h.admin({action:'delete',id:row.id})).status,400);await h.admin({action:'delete',id:row.id,confirm:true});assert(!JSON.stringify([...h.storage.map]).includes(row.email));assert(!JSON.stringify([...h.storage.map]).includes(row.name));await h.signup();assert.equal((await(await h.admin({action:'list'})).json()).total,0);});
test('Sheet export is explicit, RAW, read-back verified and private to owner',async()=>{const h=await harness();await h.signup(valid.email,{name:'=IMPORTXML("bad")'});assert.equal((await h.admin({action:'sheet'})).status,400);const r=await h.admin({action:'sheet',confirm:true}),v=await r.json();assert.equal(r.status,200);assert(v.exported);assert.deepEqual(h.sheet()[0],HEADERS);assert.equal(h.sheet()[1][2],'\'=IMPORTXML("bad")');assert.equal(h.sheet()[1][9],'NO');assert(h.sheet()[1][12].includes('manage.html#'));assert(h.googleCalls.filter(x=>x.url.includes('spreadsheets')).every(x=>!x.url.includes('access_token')));assert(!JSON.stringify([...h.storage.map]).includes('test-google-access'));});
test('failed Sheet write or read-back keeps the live list safe and reports failure',async()=>{for(const mode of ['failGoogle','badReadback']){const h=await harness();await h.signup();h[mode]();assert.equal((await h.admin({action:'sheet',confirm:true})).status,502);assert.equal((await(await h.admin({action:'list'})).json()).active,1);}});
test('formula-safe CSV and strict routes',async()=>{assert.equal(csvCell('=evil'),'"\'=evil"');assert.equal(csvCell('a"b'),'"a""b"');assert.equal(await routeSubscriptions(new Request(BASE+'/other'),{}),null);assert.equal((await routeSubscriptions(req(),{})).status,503);assert.equal((await routeSubscriptions(req('/bogus'),{})).status,404);assert.equal((await routeSubscriptions(req('',valid,{Origin:'https://bad.example'}),{})).status,403);});
