'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'public/mtgtools/odyssey');
const delivery=require('../public/mtgtools/odyssey/artwork-delivery.js');
const app=fs.readFileSync(path.join(dir,'app.html'),'utf8');
const art={id:'ART-001',source:'https://museum.example/object/1',title:'An exact artwork'};
const full='/mtgtools/odyssey/assets/artwork/ART-001.abcdef012345.full.webp',thumb='/mtgtools/odyssey/assets/artwork/ART-001.abcdef012345.thumb.webp';
const manifest={artworks:{'ART-001':{...art,status:'verified',originalUrl:'https://museum.example/art.jpg',width:3000,height:2000,full:{url:full,width:3000,height:2000},thumb:{url:thumb,width:480,height:320}}}};
test('delivery uses exact source identity, not merely a reused ART number',()=>{assert.equal(delivery.full(art,manifest),full);assert.equal(delivery.full({...art,title:'Different work'},manifest),'');assert.equal(delivery.full({...art,source:'https://other.example'},manifest),'');});
test('thumbnails have their own route and never supply print dimensions',()=>{assert.equal(delivery.thumb(art,manifest),thumb);assert.deepEqual(delivery.dimensions(art,full,manifest),{w:3000,h:2000,via:'decoded-source-audit'});assert.equal(delivery.dimensions(art,thumb,manifest),null);});
test('unverified and unsafe delivery routes never become artwork',()=>{const bad=structuredClone(manifest);bad.artworks[art.id].status='unavailable';assert.equal(delivery.full(art,bad),'');assert.equal(delivery.unavailable(art,bad),true);bad.artworks[art.id].status='verified';bad.artworks[art.id].full.url='//evil.example/image';bad.artworks[art.id].originalUrl='javascript:alert(1)';assert.equal(delivery.full(art,bad),'');});
test('external previews retain real dimensions without falsely claiming a local mirror',()=>{const d=structuredClone(manifest);delete d.artworks[art.id].full;delete d.artworks[art.id].thumb;d.artworks[art.id].width=437;d.artworks[art.id].height=600;assert.equal(delivery.full(art,d),'https://museum.example/art.jpg');assert.deepEqual(delivery.dimensions(art,delivery.full(art,d),d),{w:437,h:600,via:'decoded-source-audit'});});
test('transient failures expire and invalid or future dates cannot blacklist an image',()=>{const now=Date.parse('2026-09-19T12:00:00Z');assert.equal(delivery.freshFailure({at:'2026-09-19T11:59:00Z'},now),true);for(const at of ['2026-09-19T11:50:00Z','broken','2026-09-20T00:00:00Z'])assert.equal(delivery.freshFailure({at},now),false);});
test('resolver queue shares in-flight work and enforces its parallelism cap',async()=>{const queue=delivery.createQueue(3);let active=0,peak=0,calls=0;const work=async()=>{calls++;active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,5));active--;return 'ok';};const first=queue.run('same',work),duplicate=queue.run('same',work);assert.equal(first,duplicate);await Promise.all([first,duplicate,...Array.from({length:9},(_,i)=>queue.run('other'+i,work))]);assert.equal(calls,10);assert.ok(peak<=3);});
test('failed queued work does not strand subsequent artwork loads',async()=>{const queue=delivery.createQueue(1);const a=queue.run('bad',()=>{throw Error('failed');});const b=queue.run('good',()=>42);await assert.rejects(a,/failed/);assert.equal(await b,42);await new Promise(r=>setTimeout(r,0));assert.equal(queue.size,0);assert.equal(await queue.run('bad',()=>7),7);});
function single(name){const m=app.match(new RegExp('^function '+name+'\\([^\\n]*','m'));assert.ok(m,name);return m[0];}
test('candidate-use badges share a single index and invalidate when matching rules change',()=>{const context={CARDS:Array.from({length:309},(_,i)=>({number:i+1})),candidateUsageCache:null,candidateUsageResolver:null,calls:0};context.effectiveCandidateIds=n=>{context.calls++;return ['ART-'+n];};vm.createContext(context);vm.runInContext(single('candidateUsage')+'\n'+single('candidateUseCount'),context);for(let i=1;i<=450;i++)context.candidateUseCount('ART-'+i);assert.equal(context.calls,309);context.effectiveCandidateIds=n=>{context.calls++;return ['SHARED'];};assert.equal(context.candidateUseCount('SHARED'),309);assert.equal(context.calls,618);});
test('resolution counters scan card models once rather than per artwork',()=>{let models=0;const context={ART:Array.from({length:450},(_,i)=>({id:'ART-'+i})),CARDS:Array.from({length:309},(_,i)=>({number:i+1})),model:n=>{models++;return {artId:'ART-'+(n%450)};},directArtUrl:id=>id,artImageDims:{},OdysseyArtDelivery:{dimensions:()=>({w:3000,h:2000})},qualityAssessment:()=>({sourceExcluded:false})};vm.createContext(context);vm.runInContext(single('qualityCounts'),context);const result=context.qualityCounts();assert.equal(result.measured,450);assert.equal(models,309);});
test('Greek mana symbols preserve original bytes as independently cached assets',()=>{const data=JSON.parse(app.match(/const MANA_PIP_DATA=(\{[^\n]+\});/)[1]);assert.deepEqual(Object.keys(data).sort(),['W','U','B','R','G','C'].sort());for(const src of Object.values(data)){assert.match(src,/\/assets\/mana-pips\/[WUBRGC]\.[a-f0-9]{12}\.png$/);const bytes=fs.readFileSync(path.join(root,'public',src));assert.equal(bytes.subarray(1,4).toString(),'PNG');assert.ok(src.includes(crypto.createHash('sha256').update(bytes).digest('hex').slice(0,12)));}assert.ok(Buffer.byteLength(app)<220000);});
test('performance integration preserves crop keys and does not rewrite the card dataset',()=>{for(const key of ['odyssey-layout-overrides-v02','odyssey-art-crop-profiles-v04','odyssey-card-review-v04','odyssey-profile-review-v05','odyssey-studio-dataset-v4'])assert.ok(app.includes(key));assert.match(app,/localImageUrls\[m.number\]\|\|manual\|\|directArtUrl/);assert.match(app,/img.style.objectFit='fill'/);assert.match(app,/PRINT_DPI_MIN=240/);assert.match(app,/candidateUsageCache=null;if\(previewCropCleanup\)/);});

test('catalogue image choices route to verified full images without mutating saved edits',()=>{const saved={1:{imageUrl:'https://museum.example/original.tif',zoom:1.23,focusX:43}};const context={overrides:saved,localImageUrls:{},artById:{'ART-432':{imageUrl:'https://museum.example/original.tif'}},KNOWN_IMAGE_URLS:{},OdysseyArtDelivery:{full:()=>full,entry:()=>({originalUrl:'https://museum.example/original.tif'})},badKeyUrl:u=>u,directArtUrl:()=>full,sizedMuseumUrl:u=>u};vm.createContext(context);vm.runInContext(single('imageForArt'),context);assert.equal(context.imageForArt({number:1,artId:'ART-432',imageUrl:saved[1].imageUrl}),full);assert.equal(saved[1].imageUrl,'https://museum.example/original.tif');assert.equal(saved[1].zoom,1.23);assert.equal(saved[1].focusX,43);const custom='https://my.example/custom.jpg';assert.equal(context.imageForArt({number:1,artId:'ART-432',imageUrl:custom}),custom);context.localImageUrls[1]='blob:my-upload';assert.equal(context.imageForArt({number:1,artId:'ART-432',imageUrl:custom}),'blob:my-upload');});
