'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'public/mtgtools/odyssey');
const plan=require('../scripts/odyssey-release-cycles.json');
const read=name=>JSON.parse(fs.readFileSync(path.join(dir,'data',name),'utf8'));
const current=read('odyssey-data.json'),candidate=read('odyssey-analysis-candidate-v1.json'),candidate2=read('odyssey-analysis-candidate-v2.json');
const tally=(cards,key)=>cards.reduce((r,c)=>{const k=typeof key==='function'?key(c):c[key];r[k]=(r[k]||0)+1;return r;},{});
// The cycle plan describes the archival Candidate 1 snapshot, not the live Wave A set.
for(const [scope,d,expected] of [['Candidate',candidate,{revision:'mainset-song-cycles-v1',legendary:103}]]){
 test(scope+' contains exactly the intended release and card identities',()=>{assert.equal(d.cards.length,309);assert.equal(new Set(d.cards.map(c=>c.id)).size,309);assert.equal(d.release.revision,expected.revision);assert.deepEqual(tally(d.cards,'rarity'),{C:105,U:109,R:75,M:20});});
 test(scope+' cycle membership comes from the actual card records',()=>{for(const cycle of plan.cycles){const cards=d.cards.filter(c=>c.cycleIds?.includes(cycle.id));assert.deepEqual(cards.map(c=>c.number).sort((a,b)=>a-b),[...cycle.numbers].sort((a,b)=>a-b),cycle.id);if(cycle.rarity)assert.ok(cards.every(c=>c.rarity===cycle.rarity),cycle.id);if(cycle.rarities)assert.deepEqual(cards.map(c=>c.rarity).sort(),[...cycle.rarities].sort());}});
 test(scope+' five hybrid Sagas are songs with two listener interpretations',()=>{const cards=d.cards.filter(c=>c.cycleIds?.includes('cycle.hybrid-sagas-uncommon'));assert.equal(cards.length,5);assert.deepEqual(cards.map(c=>c.mana.match(/\{([WUBRG]\/[WUBRG])\}/)[1]).sort(),['W/U','U/R','B/R','B/G','G/W'].sort());for(const s of plan.songs){const c=cards.find(c=>c.id===s.id);assert.equal(c.name,s.title);assert.equal(c.displayName,s.title);assert.equal(c.type,'Enchantment — Saga');assert.equal(c.layout,'saga');assert.equal(c.rarity,'U');assert.equal(Object.keys(c.song.interpretations).length,2);assert.match(c.song.titleStatus,/not an ancient quotation/);assert.equal(c.rules.split('\n').length,3);}});
 test(scope+' Saga type totals do not double-count the sole DFC layout',()=>{const sagas=d.cards.filter(c=>/\bSaga\b/.test(c.type));assert.equal(sagas.length,15);assert.deepEqual(tally(sagas,'rarity'),{U:5,R:9,M:1});const dfcs=d.cards.filter(c=>c.layout==='transform'||/\/\/BACK\/\//.test(c.rules||''));assert.deepEqual(dfcs.map(c=>c.id),['ODY-229']);const layout=tally(d.cards,c=>c.layout==='transform'?'double-face-battle':c.layout||'standard');assert.deepEqual(d.ffSkeleton.actual.layouts.byLayout,layout);assert.equal(Object.values(layout).reduce((a,b)=>a+b,0),309);});
 test(scope+' audit reflects cards and keeps benchmarks separate',()=>{const legends=d.cards.filter(c=>/\bLegendary\b/.test(c.type));assert.equal(d.ffSkeleton.actual.legendaryCards,legends.length);assert.equal(legends.length,expected.legendary);assert.equal(d.ffSkeleton.target.legendaryCards,105);assert.deepEqual(d.ffSkeleton.actual.legendaryByRarity,tally(legends,'rarity'));for(const p of d.ffSkeleton.showcasePrograms.filter(p=>!p.physicalCardId)){const ids=d.cards.filter(c=>c.showcase?.includes(p.id)).map(c=>c.id);assert.equal(p.count,ids.length);assert.deepEqual(p.cardIds,ids);}assert.deepEqual(d.storyApportionment.actual,tally(d.cards,'narrativeEra'));});
 test(scope+' data integrity is reproducible from the documented scope',()=>{assert.equal(d.integrity.sha256Scope,'cards-json-stringify-utf8-v1');assert.equal(d.integrity.sha256,createHash('sha256').update(JSON.stringify(d.cards)).digest('hex'));});
}
test('Current identifies the authorized Wave A set and preserves all card slots',()=>{assert.equal(current.datasetVersion,'2026-09-26.1');assert.equal(current.release.revision,'wave-a-live-20260926-v1');assert.equal(current.release.publishedFrom,'14A2-live-sheet');assert.equal(current.cards.length,309);assert.equal(new Set(current.cards.map(c=>c.id)).size,309);assert.deepEqual(current.cards.map(c=>c.number),Array.from({length:309},(_,i)=>i+1));assert.deepEqual(tally(current.cards,'rarity'),{C:106,U:109,R:74,M:20});assert.match(current.cards[207].type,/Enchantment Creature — Saga/);assert.equal(current.cards[228].layout,'transform');});
test('Current cycles retain their actual Wave A membership',()=>{const byId=new Map(current.cards.map(c=>[c.id,c]));for(const c of current.cards)for(const id of c.cycleIds||[])assert.equal(typeof id,'string',c.id);assert.deepEqual(current.cards.filter(c=>c.cycleIds?.includes('ff-analog-gold-signposts')).map(c=>c.number),[51,52,53,55,56,58,59,60,90,91,148,153,157,159,173,175,176,177,178,179]);assert.deepEqual(current.cards.filter(c=>c.cycleIds?.includes('cycle.hybrid-sagas-uncommon')).map(c=>c.number),[97,162,163,232,245]);assert.equal(byId.size,309);});
test('Current five hybrid Sagas have distinct two-colour costs and three chapters',()=>{const cards=current.cards.filter(c=>c.cycleIds?.includes('cycle.hybrid-sagas-uncommon'));assert.deepEqual(cards.map(c=>c.mana.match(/\{([WUBRG]\/\w)\}/)?.[1]).sort(),['U/R','B/G','R/W','W/B','G/U'].sort());for(const c of cards){assert.equal(c.type,'Enchantment — Saga');assert.equal(c.layout,'saga');assert.equal(c.rarity,'U');assert.match(c.rules,/\bI\s*—/);assert.match(c.rules,/\bII\s*—/);assert.match(c.rules,/\bIII\s*—/);}});
test('Current Saga and transform totals are checked independently',()=>{const sagas=current.cards.filter(c=>/\bSaga\b/.test(c.type));assert.equal(sagas.length,17);assert.deepEqual(tally(sagas,'rarity'),{U:7,R:8,M:2});assert.deepEqual(current.cards.filter(c=>c.layout==='transform').map(c=>c.number),[229]);const layout=tally(current.cards,c=>c.layout==='transform'?'double-face-battle':c.layout||'standard');assert.deepEqual(current.ffSkeleton.actual.layouts.byLayout,layout);assert.equal(Object.values(layout).reduce((a,b)=>a+b,0),309);});
test('Current Saga records use a Saga layout except the transforming battle',()=>{for(const c of current.cards.filter(c=>/\bSaga\b/.test(c.type)))assert.equal(c.layout,c.number===229?'transform':'saga',c.id);assert.equal(current.cards[207].pt,'5/7');});
test('Current card records retain the published legendary total',()=>{const legends=current.cards.filter(c=>/\bLegendary\b/.test(c.type));assert.equal(legends.length,91);assert.equal(current.ffSkeleton.target.legendaryCards,105);});
test('Current derived audit is synchronized with card records',()=>{const legends=current.cards.filter(c=>/\bLegendary\b/.test(c.type));assert.equal(current.ffSkeleton.actual.legendaryCards,legends.length,'legendary total');assert.deepEqual(current.ffSkeleton.actual.legendaryByRarity,{C:0,...tally(legends,'rarity')});assert.deepEqual(current.storyApportionment.actual,tally(current.cards,'narrativeEra'));for(const p of current.ffSkeleton.showcasePrograms.filter(p=>!p.physicalCardId)){const ids=current.cards.filter(c=>c.showcase?.includes(p.id)).map(c=>c.id);assert.equal(p.count,ids.length,p.id);assert.deepEqual(p.cardIds,ids,p.id);}assert.equal(current.release.knownBenchmarkDifferences.legendaryCards.actual,legends.length);});
test('Current data integrity is reproducible from its cards',()=>{assert.equal(current.integrity.sha256Scope,'cards-json-stringify-utf8-v1');assert.equal(current.integrity.sha256,createHash('sha256').update(JSON.stringify(current.cards)).digest('hex'));});
test('bundled JavaScript and JSON are exactly the same dataset',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(dir,'data/odyssey-data.js'),'utf8'),context);assert.equal(JSON.stringify(context.window.ODYSSEY_DATA),JSON.stringify(current));});
test('Candidate releases remain available as archival snapshots',()=>{assert.equal(candidate.datasetVersion,'analysis-candidate-v1');assert.equal(candidate2.datasetVersion,'analysis-candidate-v2');assert.notDeepEqual(current.cards,candidate.cards);assert.equal(candidate2.cards.length,309);assert.equal(candidate2.candidate.cutoverAuthorized,true);assert.equal(candidate2.candidate.productionFilesModified,true);const app=fs.readFileSync(path.join(dir,'app.html'),'utf8');assert.match(app,/value="analysis-candidate-v2"/);assert.match(app,/ANALYSIS_CANDIDATE_V2_URL/);assert.match(app,/value==='analysis-candidate-v1'\|\|value==='analysis-candidate-v2'/);});
test('current artwork coverage admits known blanks but never points to missing art',()=>{assert.ok(current.artworks.length>=553);assert.equal(current.coverage.length,309);const art=new Set(current.artworks.map(a=>a.id)),coverage=new Map(current.coverage.map(c=>[c.number,c]));assert.equal(art.size,current.artworks.length);let blanks=0;for(const c of current.cards){const row=coverage.get(c.number);assert.ok(row,c.id+' coverage');assert.equal(row.name,c.displayName,'coverage uses the displayed alias');assert.equal(row.primary,c.primaryArt);if(!c.primaryArt){blanks++;continue;}assert.ok(art.has(c.primaryArt),c.id+' artwork');assert.ok(row.candidateIds.includes(row.primary),c.id+' candidate');}assert.ok(blanks<=29,'art coverage must not regress from the earlier audit');});
test('release asset versions refresh without removing saved-data keys',()=>{const app=fs.readFileSync(path.join(dir,'app.html'),'utf8');assert.match(app,/odyssey-data\.js\?v=20260926-saga1/);assert.match(app,/transform-faces\.js\?v=20260927-battle1/);assert.match(app,/odyssey-analysis-candidate-v1\.json\?v=20260920-empty1/);assert.match(app,/odyssey-studio-dataset-v4/);assert.match(app,/function resetBundledDataset\(/);const index=fs.readFileSync(path.join(dir,'index.html'),'utf8');assert.match(index,/app\.html\?v=20260927-battle1/);assert.match(index,/OdysseyArtTransfer\.prepare/);});
test('the sole transform card has an explicit Studio render route',()=>{const card=candidate2.cards.find(c=>c.layout==='transform');assert.equal(card?.number,229);assert.match(card.rules,/\/\/BACK\/\//);const app=fs.readFileSync(path.join(dir,'app.html'),'utf8');assert.match(app,/<option>transform<\/option>/);assert.match(app,/m\.layout==='transform'&&main\.includes\('\/\/BACK\/\/'\)/);assert.match(app,/const displayName=m\.layout==='transform'/);const frames=fs.readFileSync(path.join(dir,'frame-system.js'),'utf8');assert.match(frames,/traits\.push\('transform'\)/);assert.match(frames,/split\('\/\/BACK\/\/'\)\[0\]/);});
