'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'public/mtgtools/odyssey');
const plan=require('../scripts/odyssey-release-cycles.json');
const read=name=>JSON.parse(fs.readFileSync(path.join(dir,'data',name),'utf8'));
const current=read('odyssey-data.json'),candidate=read('odyssey-analysis-candidate-v1.json');
const tally=(cards,key)=>cards.reduce((r,c)=>{const k=typeof key==='function'?key(c):c[key];r[k]=(r[k]||0)+1;return r;},{});
for(const [scope,d] of [['Current',current],['Candidate',candidate]]){
 test(scope+' contains exactly the intended release and card identities',()=>{assert.equal(d.cards.length,309);assert.equal(new Set(d.cards.map(c=>c.id)).size,309);assert.equal(d.release.revision,'mainset-song-cycles-v1');assert.deepEqual(tally(d.cards,'rarity'),{C:106,U:109,R:74,M:20});});
 test(scope+' cycle membership comes from the actual card records',()=>{for(const cycle of plan.cycles){const cards=d.cards.filter(c=>c.cycleIds?.includes(cycle.id));assert.deepEqual(cards.map(c=>c.number).sort((a,b)=>a-b),[...cycle.numbers].sort((a,b)=>a-b),cycle.id);if(cycle.rarity)assert.ok(cards.every(c=>c.rarity===cycle.rarity),cycle.id);if(cycle.rarities)assert.deepEqual(cards.map(c=>c.rarity).sort(),[...cycle.rarities].sort());}});
 test(scope+' five hybrid Sagas are songs with two listener interpretations',()=>{const cards=d.cards.filter(c=>c.cycleIds?.includes('cycle.hybrid-sagas-uncommon'));assert.equal(cards.length,5);assert.deepEqual(cards.map(c=>c.mana.match(/\{([WUBRG]\/[WUBRG])\}/)[1]).sort(),['W/U','U/R','B/R','B/G','G/W'].sort());for(const s of plan.songs){const c=cards.find(c=>c.id===s.id);assert.equal(c.name,s.title);assert.equal(c.displayName,s.title);assert.equal(c.type,'Enchantment — Saga');assert.equal(c.layout,'saga');assert.equal(c.rarity,'U');assert.equal(Object.keys(c.song.interpretations).length,2);assert.match(c.song.titleStatus,/not an ancient quotation/);assert.equal(c.rules.split('\n').length,3);}});
 test(scope+' Saga type totals do not double-count the sole DFC layout',()=>{const sagas=d.cards.filter(c=>/\bSaga\b/.test(c.type));assert.equal(sagas.length,15);assert.deepEqual(tally(sagas,'rarity'),{U:5,R:9,M:1});const dfcs=d.cards.filter(c=>c.layout==='transform'||/\/\/BACK\/\//.test(c.rules||''));assert.deepEqual(dfcs.map(c=>c.id),['ODY-229']);const layout=tally(d.cards,c=>c.layout==='transform'?'double-face-battle':c.layout||'standard');assert.deepEqual(d.ffSkeleton.actual.layouts.byLayout,layout);assert.equal(Object.values(layout).reduce((a,b)=>a+b,0),309);});
 test(scope+' audit reflects cards and keeps benchmarks separate',()=>{const legends=d.cards.filter(c=>/\bLegendary\b/.test(c.type));assert.equal(d.ffSkeleton.actual.legendaryCards,legends.length);assert.equal(legends.length,103);assert.equal(d.ffSkeleton.target.legendaryCards,105);assert.deepEqual(d.ffSkeleton.actual.legendaryByRarity,tally(legends,'rarity'));for(const p of d.ffSkeleton.showcasePrograms.filter(p=>!p.physicalCardId)){const ids=d.cards.filter(c=>c.showcase?.includes(p.id)).map(c=>c.id);assert.equal(p.count,ids.length);assert.deepEqual(p.cardIds,ids);}assert.deepEqual(d.storyApportionment.actual,tally(d.cards,'narrativeEra'));});
 test(scope+' data integrity is reproducible from the documented scope',()=>{assert.equal(d.integrity.sha256Scope,'cards-json-stringify-utf8-v1');assert.equal(d.integrity.sha256,createHash('sha256').update(JSON.stringify(d.cards)).digest('hex'));});
}
test('bundled JavaScript and JSON are exactly the same dataset',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(dir,'data/odyssey-data.js'),'utf8'),context);assert.equal(JSON.stringify(context.window.ODYSSEY_DATA),JSON.stringify(current));});
test('Current and Candidate remain separately identified with the same released cards',()=>{assert.equal(current.datasetVersion,'2026-09-19.3');assert.equal(candidate.datasetVersion,'analysis-candidate-v1');assert.equal(candidate.candidate.productionDatasetVersion,current.datasetVersion);assert.deepEqual(current.cards,candidate.cards);});
test('every card keeps an artwork and renamed coverage remains aligned',()=>{assert.equal(current.artworks.length,458);assert.equal(current.coverage.length,309);const art=new Set(current.artworks.map(a=>a.id));for(const c of current.cards){assert.ok(art.has(c.primaryArt),c.id+' artwork');const coverage=current.coverage.find(row=>row.number===c.number);assert.equal(coverage.name,c.name);assert.ok(coverage.candidateIds.includes(coverage.primary));}});
test('release asset versions refresh without removing saved-data keys',()=>{const app=fs.readFileSync(path.join(dir,'app.html'),'utf8');assert.match(app,/odyssey-data\.js\?v=20260919-live3/);assert.match(app,/odyssey-analysis-candidate-v1\.json\?v=20260919-refinement/);assert.match(app,/odyssey-studio-dataset-v4/);assert.match(app,/function resetBundledDataset\(/);const index=fs.readFileSync(path.join(dir,'index.html'),'utf8');assert.match(index,/app\.html\?v=20260919-20/);assert.match(index,/OdysseyArtTransfer\.prepare/);});
