'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../public/mtgtools/odyssey/art-placement-core.js');
const sample=(extra={})=>({...P.capture({id:'ODY-061',artId:'ART-245',layout:'standard',zoom:1.65,focusX:-37.5,focusY:0,fit:'cover'},'https://kliawota.design/art.webp'),...extra});
const change=(after,before=null)=>({before,after});
const headers={origin:'https://kliawota.design',authorization:'Bearer test-google-credential', 'content-type':'application/json'};
const req=(action,changes=[])=>new Request('https://kliawota.design'+P.API,{method:'POST',headers,body:JSON.stringify({action,changes})});
async function harness(initial=null){
 const {placementWorkspace,routePlacements}=await import('../src/odyssey-placement.mjs');
 const store=new Map(),calls=[],writes=[];let rows=initial&&structuredClone(initial),badReadback=false,denied=0;
 const storage={get:async k=>structuredClone(store.get(k)),put:async(k,v)=>{store.set(k,structuredClone(v));}};
 async function google(url,opts){
  assert(url.startsWith('https://sheets.googleapis.com/v4/spreadsheets/'+P.SHEET_ID));
  assert.equal(opts.headers.Authorization,headers.authorization);calls.push({url,method:opts.method||'GET'});
  if(denied)return Response.json({error:'secret token must not be echoed'},{status:denied});
  if(url.includes('?fields='))return Response.json({sheets:rows?[{properties:{title:P.TAB,sheetId:123,gridProperties:{rowCount:2001,columnCount:13}}}]:[]});
  if(url.endsWith(':batchUpdate')&&!url.includes('/values:')){const b=JSON.parse(opts.body);assert.equal(b.requests[0].addSheet.properties.title,P.TAB);rows=[];writes.push(b);return Response.json({});}
  if(url.endsWith('/values:batchUpdate')){const b=JSON.parse(opts.body);assert.equal(b.valueInputOption,'RAW');writes.push(b);for(const d of b.data){const n=Number(d.range.match(/!A(\d+):/)[1]);while(rows.length<n)rows.push([]);rows[n-1]=structuredClone(d.values[0]);}if(badReadback&&rows.length>1)rows[1][7]=3.333;return Response.json({});}
  return Response.json({values:rows});
 }
 return {calls,writes,store,routePlacements,storage,post:async(a,c=[])=>placementWorkspace(req(a,c),storage,google),get:()=>placementWorkspace(new Request('https://kliawota.design'+P.API),storage,google),rows:()=>rows,tamper:r=>rows=r,deny:n=>denied=n,bad:()=>badReadback=true};
}
test('placement roundtrip preserves fractional zoom, negative pan and zero',()=>{const r=sample();assert(P.valid(r));assert.deepEqual(P.parseRows([P.HEADERS,P.toRow(r)]).records[P.key(r)],r);assert.equal(r.focusY,0);assert(P.equal(r,{...r,revision:12,updatedAt:'different'}));});
for(const [label,extra]of Object.entries({nan:{zoom:NaN},infinity:{focusX:Infinity},tiny:{zoom:0},large:{zoom:21},missing:{fit:undefined},url:{sourceUrl:'javascript:alert(1)'},card:{cardId:'__proto__'},art:{artId:'bad'},face:{face:'sideways'},assignment:{imageUrl:'https://example.com'},rules:{rules:'PRIVATE'}}))test('rejects '+label,()=>assert.throws(()=>P.normalize(sample(extra))));
test('only geometry applies; assignments and text are immutable',()=>{const m={id:'ODY-061',artId:'ART-245',layout:'standard',rules:'unchanged',imageUrl:'unchanged'};const r=sample();const result=P.apply(m,{[P.key(r)]:r},r.sourceUrl);assert.equal(result.zoom,1.65);assert.equal(result.rules,m.rules);assert.equal(result.imageUrl,m.imageUrl);assert.equal(result.artId,m.artId);});
for(const [label,extra,source]of [['card',{id:'ODY-062'}],['art',{artId:'ART-246'}],['layout',{layout:'saga'}],['face',{faceRole:'back'}],['source',{},'https://example.com/replacement.jpg']])test('stale '+label+' guard',()=>{const m={id:'ODY-061',artId:'ART-245',layout:'standard',...extra},r=sample();assert.equal(P.apply(m,{[P.key(r)]:r},source||r.sourceUrl),m);});
test('front and back rows are independent; default resets are explicit',()=>{const f=sample(),b=sample({face:'back',zoom:1,focusX:0,focusY:0,fit:'contain'});const rows=P.parseRows([P.HEADERS,P.toRow(b),P.toRow(f)]);assert.equal(rows.positions[P.key(f)],3);assert.equal(rows.positions[P.key(b)],2);assert.equal(P.apply({id:f.cardId,artId:f.artId,layout:f.layout,faceRole:'back'},rows.records,b.sourceUrl).zoom,1);});
test('rejects wrong headers, duplicates, blank numeric cells and snapshot keys',()=>{const r=sample();assert.throws(()=>P.parseRows([['x']]));assert.throws(()=>P.parseRows([P.HEADERS,P.toRow(r),P.toRow(r)]));const blank=P.toRow(r);blank[7]='';assert.throws(()=>P.parseRows([P.HEADERS,blank]));assert.throws(()=>P.snapshot({...P.empty(),records:{wrong:r}}));});
test('three-way review keeps null creation baselines and refuses silent overwrite',()=>{const a=sample(),b=sample({zoom:2}),c=sample({zoom:3});assert.equal(P.analyze({},[change(a)]).writes.length,1);assert.equal(P.analyze({[P.key(a)]:a},[change(a)]).already.length,1);assert.equal(P.analyze({[P.key(a)]:b},[change(c,a)]).conflicts.length,1);assert.equal(P.analyze({[P.key(a)]:b},[change(c)]).conflicts.length,1);assert.throws(()=>P.analyze({},[change(a),change(a)]));});
test('public GET is empty by default and never touches Google',async()=>{const h=await harness();assert.deepEqual(await(await h.get()).json(),P.empty());assert.equal(h.calls.length,0);});
test('review is read-only; publish creates only the placement tab and verifies it',async()=>{const h=await harness(),r=sample();let v=await(await h.post('review',[change(r)])).json();assert.equal(v.writes.length,1);assert.equal(h.writes.length,0);v=await(await h.post('publish',[change(r)])).json();assert.equal(v.verified,true);assert.equal(v.records[P.key(r)].zoom,r.zoom);assert.equal(v.records[P.key(r)].revision,1);assert.equal(h.rows()[0][0],'Card ID');assert.equal(h.store.size,1);assert(!JSON.stringify([...h.store]).includes('credential'));assert.equal((await(await h.get()).json()).revision,1);});
test('publishing is idempotent and only requested rows are written',async()=>{const a=sample(),b=sample({cardId:'ODY-062'}),next=sample({zoom:2});const h=await harness([P.HEADERS,P.toRow(b),P.toRow(a)]);let v=await(await h.post('publish',[change(next,a)])).json();assert(v.verified);assert.equal(h.writes[0].data.length,1);assert.equal(h.writes[0].data[0].range,"'Artwork Placement'!A3:M3");assert.deepEqual(h.rows()[1],P.toRow(b));v=await(await h.post('publish',[change(next,a)])).json();assert.equal(v.written,0);assert.equal(h.writes.length,1);});
test('conflict is returned before any Sheet or public write',async()=>{const a=sample(),b=sample({zoom:2}),h=await harness([P.HEADERS,P.toRow(b)]);const r=await h.post('publish',[change(sample({zoom:3}),a)]);assert.equal(r.status,409);assert.equal(h.writes.length,0);assert.equal(h.store.size,0);});
test('a failed readback never promotes an unverified crop',async()=>{const a=sample(),h=await harness([P.HEADERS,P.toRow(a)]);await h.post('refresh');const before=await(await h.get()).json();h.bad();const r=await h.post('publish',[change(sample({zoom:2}),a)]);assert.equal(r.status,502);assert.deepEqual(await(await h.get()).json(),before);});
test('Sheet refresh publishes only canonical Sheet rows, never client payload',async()=>{const a=sample(),h=await harness([P.HEADERS,P.toRow(a)]);assert.equal((await h.post('refresh',[change(a)])).status,400);const r=await h.post('refresh');assert.equal((await r.json()).records[P.key(a)].zoom,1.65);assert.equal(h.writes.length,0);});
for(const status of [401,403,500])test('Google '+status+' does not leak credentials or overwrite public state',async()=>{const h=await harness();h.deny(status);const r=await h.post('publish',[change(sample())]);assert.equal(r.status,status===500?502:status);assert(!JSON.stringify(await r.json()).includes('test-google-credential'));assert.equal(h.store.size,0);});
test('fixed route requires origin/auth, rejects other methods and leaves unrelated routes alone',async()=>{const h=await harness();assert.equal(await h.routePlacements(new Request('https://kliawota.design/unrelated'),{}),null);assert.equal((await h.routePlacements(new Request('https://kliawota.design'+P.API,{method:'DELETE'}),{})).status,405);assert.equal((await h.routePlacements(new Request('https://kliawota.design'+P.API,{method:'POST'}),{})).status,403);assert.equal((await h.routePlacements(new Request('https://kliawota.design'+P.API,{method:'POST',headers:{origin:'https://kliawota.design'}}),{})).status,401);assert.equal((await h.routePlacements(req('review'),{})).status,503);});
test('same-origin source identity survives production and preview hostnames',()=>{const r=sample({sourceUrl:'/mtgtools/odyssey/assets/artwork/ART-162.43e8f25cdc80.full.webp'});assert(P.valid(r));assert(!P.valid({...r,sourceUrl:'//evil.example/image.webp'}));assert(!P.valid({...r,sourceUrl:'/mtgtools/odyssey/assets/artwork/../../secret'}));});
