const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../public/mtgtools/odyssey/art-sync-core.js');
const polish=require('../public/mtgtools/odyssey/studio-polish.js');
const sync=require('../public/mtgtools/odyssey/art-sync.js');
const artwork=require('../public/mtgtools/odyssey/artwork-tools.js');
const key='current:card:ODY-001',crop='current:crop:ART-001|standard|normal';
for(const [input,expected]of [['2WU','{2}{W}{U}'],['{w/u}{2} X','{W/U}{2}{X}'],['{tap}','{T}'],['10{C}','{10}{C}'],['W/U/P','{W/U/P}'],['—',''],['WRONG!','WRONG!']])test('canonical mana: '+input,()=>assert.equal(polish.normalizeCost(input),expected));
for(const [input,expected]of [['T: Add U.','{T}: Add {U}.'],['6U: Draw a card.','{6}{U}: Draw a card.'],['Foretell 1U. Tap target creature.','Foretell {1}{U}. Tap target creature.'],['This spell costs 1W more.','This spell costs {1}{W} more.'],['Sacrifice two creatures.','Sacrifice two creatures.'],['Flying. T: Add G.','Flying. {T}: Add {G}.'],['Spell — 2U — Sorcery','Spell — {2}{U} — Sorcery'],['1B, T, Exile another card: Draw a card.','{1}{B}, {T}, Exile another card: Draw a card.'],['G, T, Sacrifice this creature: Destroy target enchantment.','{G}, {T}, Sacrifice this creature: Destroy target enchantment.'],['1, T, Sacrifice this artifact: Draw a card.','{1}, {T}, Sacrifice this artifact: Draw a card.'],['Equip 2.','Equip {2}.']])test('rules encoding: '+input,()=>assert.equal(polish.normalizeRules(input),expected));
test('hybrid remains a single top-level symbol',()=>assert.equal((polish.costHTML('W/U').match(/data-symbol=/g)||[]).length,1));
test('tap and untap have vector glyphs and accessible names',()=>{for(const t of ['T','Q'])assert.match(polish.symbolHTML(t,true),/<svg/);assert.match(polish.symbolHTML('T',true),/aria-label="Tap"/)});
test('unsafe and unknown text remains escaped',()=>{assert.ok(!polish.costHTML('<script>x</script>').includes('<script>'));assert.match(polish.rulesHTML('{BOGUS}'),/\{BOGUS\}/)});
test('pairing key is private hash, not arbitrary query',()=>{const t='a'.repeat(64);assert.equal(sync.parseKey('https://example.com/#odyssey-sync='+t),t);assert.equal(sync.parseKey(t),t);assert.equal(sync.parseKey('https://example.com/?key='+t),'')});
test('valid schema excludes card design and local image blobs',()=>{assert.equal(core.validValue(key,{zoom:2,artId:'ART-002'}),true);for(const v of [{rules:'x'},{layout:'battle'},{imageUrl:'blob:test'},{zoom:Infinity},{zoom:-1},{focusX:'2'}])assert.equal(core.validValue(key,v),false);assert.equal(core.validValue(crop,{zoom:2,fit:'cover',updated:'2026',fromCard:1}),true)});
test('invalid keys cannot cross scope or prototypes',()=>{for(const k of ['__proto__','custom:card:ODY-001','current:card:../../x'])assert.equal(core.validKey(k),false)});
test('Candidate 2 has a valid isolated art-sync scope',()=>{assert.equal(core.validKey('analysis-candidate-v2:card:ODY-001'),true);assert.equal(core.validKey('analysis-candidate-v2:crop:ART-001|saga|normal'),true);const fs=require('node:fs'),path=require('node:path');const source=fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/art-sync.js'),'utf8');assert.match(source,/state\.candidateVersion/);assert.match(source,/analysis-candidate-v2/)});
test('first local edits upload without treating another card as changed',()=>{const r=core.reconcile({}, {[key]:{zoom:2}},{});assert.equal(r.pending.length,1);assert.equal(r.conflicts.length,0)});
test('first shared edits download',()=>{const r=core.reconcile({}, {},{[key]:{revision:1,value:{zoom:2}}});assert.deepEqual(r.local[key],{zoom:2});assert.deepEqual(r.downloaded,[key])});
test('concurrent first edits are conflicts, never last-writer-wins',()=>{const r=core.reconcile({}, {[key]:{zoom:3}},{[key]:{revision:1,value:{zoom:2}}});assert.equal(r.conflicts.length,1);assert.equal(r.local[key].zoom,3);assert.equal(r.pending.length,0)});
test('reset becomes a revisioned tombstone',()=>{const b={[key]:{revision:1,value:{zoom:2}}},r=core.reconcile(b,{},b);const a=core.applyChanges(b,r.pending);assert.equal(a.records[key].revision,2);assert.equal(a.records[key].value,null)});
test('remote reset applies when local unchanged',()=>{const b={[key]:{revision:1,value:{zoom:2}}};const r=core.reconcile(b,{[key]:{zoom:2}},{[key]:{revision:2,value:null}});assert.equal(r.local[key],undefined)});
test('stale writes are rejected and retries idempotent',()=>{const r={[key]:{revision:2,value:{zoom:3}}};assert.equal(core.applyChanges(r,[{key,baseRevision:1,value:{zoom:4}}]).conflicts[key].revision,2);assert.equal(core.applyChanges(r,[{key,baseRevision:1,value:{zoom:3}}]).accepted[key].revision,2)});
test('edit during upload remains pending after exact acknowledgement',()=>{const r={[key]:{revision:2,value:{zoom:3}}};const m=core.reconcile(r,{[key]:{zoom:4}},r);assert.equal(m.pending[0].value.zoom,4);assert.equal(m.conflicts.length,0)});
test('independent cards and dataset scopes merge',()=>{const other='analysis-candidate-v1:card:ODY-001';const r=core.reconcile({}, {[key]:{zoom:2}},{[other]:{revision:1,value:{zoom:3}}});assert.equal(r.pending.length,1);assert.equal(r.local[other].zoom,3);assert.equal(r.conflicts.length,0)});
test('duplicate or oversized batches fail atomically',()=>{const change={key,baseRevision:0,value:{zoom:2}};assert.throws(()=>core.applyChanges({},[change,change]));assert.throws(()=>core.applyChanges({},Array(65).fill(change)))});
test('storage failure rolls back all previously written stores',()=>{let data={a:'1',b:'2'},failed=false;const storage={getItem:k=>data[k]??null,removeItem:k=>delete data[k],setItem(k,v){if(k==='b'&&!failed){failed=true;throw new Error('full')}data[k]=v}};assert.throws(()=>sync.writeBatch(storage,{a:3,b:4}));assert.deepEqual(data,{a:'1',b:'2'})});
class Storage{constructor(){this.map=new Map()}async get(k){return this.map.get(k)}async put(k,v){this.map.set(k,structuredClone(v))}async delete(k){this.map.delete(k)}async list({prefix}){return new Map([...this.map].filter(([k])=>k.startsWith(prefix)))}async transaction(fn){const old=structuredClone(this.map);try{return await fn(this)}catch(e){this.map=old;throw e}}}
const endpoint='https://example.com/mtgtools/odyssey/api/art-sync';
test('backend persistence, auth, isolation and validation',async()=>{
 const {handleSync,OdysseyArtWorkspace}=await import('../src/odyssey-sync.mjs');const map=new Map();const env={ODYSSEY_ART_SYNC:{idFromName:x=>x,get(id){if(!map.has(id))map.set(id,new OdysseyArtWorkspace({storage:new Storage()}));return map.get(id)}}};
 const req=(token,method='GET',changes)=>new Request(endpoint,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:changes?JSON.stringify({changes}):undefined});
 assert.equal((await handleSync(new Request(endpoint),env)).status,401);
 assert.equal((await handleSync(new Request(endpoint,{headers:{Origin:'https://evil.test'}}),env)).status,403);
 assert.equal(await handleSync(new Request('https://example.com/other'),env),null);
 assert.equal((await handleSync(req('a'.repeat(64)),{})).status,503);
 const first=await handleSync(req('a'.repeat(64),'PATCH',[{key,baseRevision:0,value:{zoom:2}}]),env);assert.equal(first.status,200);assert.equal((await first.json()).records[key].revision,1);
 assert.equal((await(await handleSync(req('a'.repeat(64)),env)).json()).records[key].value.zoom,2);
 assert.deepEqual((await(await handleSync(req('b'.repeat(64)),env)).json()).records,{});
 assert.equal((await handleSync(req('a'.repeat(64),'PATCH',[{key,baseRevision:1,value:{rules:'bad'}}]),env)).status,400);
 assert.equal((await handleSync(req('a'.repeat(64),'PATCH',[{key,baseRevision:1,value:{credit:'x'.repeat(140000)}}]),env)).status,400);
});

test('bundled datasets store canonical symbol notation',()=>{const fs=require('node:fs'),path=require('node:path');for(const file of ['public/mtgtools/odyssey/data/odyssey-data.json','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json']){const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..',file),'utf8'));assert.equal(data.symbolEncoding,'mtg-brace-v1');for(const card of data.cards){assert.equal(card.mana,polish.normalizeCost(card.mana),file+' mana '+card.number);assert.equal(card.rules,polish.normalizeRules(card.rules),file+' rules '+card.number)}}});

test('artwork search covers suggested-style metadata and full library',()=>{const fs=require('node:fs'),path=require('node:path');const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-data.json'),'utf8'));assert.equal(artwork.searchArtworks(data.artworks,'').length,data.artworks.length);const odysseus=artwork.searchArtworks(data.artworks,'odysseus');assert.ok(odysseus.length>5);assert.ok(odysseus.slice(0,10).some(a=>/odysseus|ulysses/i.test([a.title,a.tags,a.candidateCards].join(' '))));const artist=artwork.searchArtworks(data.artworks,'angelica kauffmann');assert.ok(artist.length>=2);assert.ok(artist.every(a=>/angelica kauffmann/i.test(a.artist||'')))});
test('artwork chooser exposes search-all and subtle assignment marker',()=>{const fs=require('node:fs'),path=require('node:path');const source=fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/artwork-tools.js'),'utf8');assert.match(source,/data-art-search-scope="all">Search all/);assert.match(source,/art-option-use-indicator/);assert.match(source,/Already assigned to/)});

test('FINAL FANTASY skeleton candidate stays at 309 with single-face substitution',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));assert.equal(d.cards.length,309);assert.deepEqual(d.ffSkeleton.actual.rarity,{C:105,U:109,R:75,M:20});assert.equal(d.ffSkeleton.actual.layouts.singleFace,308);assert.equal(d.ffSkeleton.actual.layouts.doubleFace,1);assert.deepEqual(d.ffSkeleton.actual.layouts.byLayout,{standard:275,saga:14,vehicle:10,adventure:8,prepare:1,'double-face-battle':1});const dfcs=d.cards.filter(c=>c.layout==='transform'||/\/\/BACK\/\//.test(c.rules||''));assert.equal(dfcs.length,1);assert.equal(dfcs[0].id,'ODY-229');assert.equal(d.ffSkeleton.actual.lands,40);assert.equal(d.ffSkeleton.actual.legendaryCards,103);assert.equal(d.ffSkeleton.actual.sixPlusManaValue,32);assert.equal(d.ffSkeleton.actual.manaCurve['2'],57);assert.equal(d.ffSkeleton.actual.manaCurve['6'],18);assert.equal(d.ffSkeleton.actual.manaCurve['7+'],14);assert.equal(d.ffSkeleton.actual.goldUncommonLegendarySignposts,20);for(const n of Object.values(d.ffSkeleton.actual.signpostPairs))assert.equal(n,2);assert.equal(d.ffSkeleton.showcasePrograms.find(x=>x.id==='greek-vase-showcase').count,48);assert.equal(d.ffSkeleton.showcasePrograms.find(x=>x.id==='character-showcase').count,31);assert.equal(d.ffSkeleton.showcasePrograms.find(x=>x.id==='master-artist').count,10);assert.equal(d.ffSkeleton.showcasePrograms.find(x=>x.id==='extended-art-legend').count,93);assert.equal(d.ffSkeleton.bonusSheet.cards.length,64);assert.deepEqual(d.ffSkeleton.target.commanderDecks,{count:4,cardsEach:100,newCardsEach:25,totalNewCardsAcrossDecks:100});});
test('Studio no longer hardcodes a 250-card candidate ceiling',()=>{const fs=require('node:fs'),path=require('node:path');const src=fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/app.html'),'utf8');assert.match(src,/Math\.min\(CARDS\.length,n\)/);assert.match(src,/\$\{CARDS\.length\}/);assert.doesNotMatch(src,/Math\.min\(250,n\)/);assert.match(src,/addedCoverage=candidate\.cards\.filter/);});

test('candidate permits exactly one DFC: the Troy battle',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));const dfcs=d.cards.filter(card=>card.layout==='transform'||/\/\/BACK\/\//.test(card.rules||''));assert.equal(dfcs.length,1);assert.equal(dfcs[0].id,'ODY-229');assert.equal(dfcs[0].name,'The Siege of Troy // The Wooden Horse');for(const card of d.cards.filter(c=>c.id!=='ODY-229')){assert.notEqual(card.layout,'transform',card.id);assert.equal(card.backFacePlan,undefined,card.id);assert.equal(card.meldPair,undefined,card.id);assert.doesNotMatch(card.rules||'',/\/\/BACK\/\//,card.id)}assert.equal(d.ffSkeleton.actual.layouts.singleFace,308);assert.equal(d.ffSkeleton.actual.layouts.doubleFace,1)});

test('story apportionment keeps outer-era material capped while prioritizing the Odyssey core',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));const counts=d.cards.reduce((m,c)=>(m[c.narrativeEra]=(m[c.narrativeEra]||0)+1,m),{});assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),309);assert.equal(counts['Iliad + young Odysseus'],46);assert.ok(counts['Odyssey']>=217);assert.ok(counts['Old Odysseus beyond the Odyssey']<=46);assert.deepEqual(d.storyApportionment.actual,counts);assert.equal(d.storyApportionment.totalCards,309);for(const c of d.cards){assert.ok(c.storyTarget,c.id);assert.ok(c.storySourceBand,c.id)}});

test('story retheme pass is complete and outer-era art review state is tracked',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));assert.equal(d.cards.filter(c=>c.storyRethemeRequired).length,0);const outerEra=d.cards.filter(c=>c.narrativeEra!=='Odyssey');assert.equal(outerEra.filter(c=>typeof c.artReviewRequired==='boolean').length,outerEra.length);assert.equal(d.storyApportionment.rethemeStatus.outerEraCards,outerEra.length);assert.equal(d.storyApportionment.rethemeStatus.outerEraArtReviewRequired,outerEra.filter(c=>c.artReviewRequired).length);assert.equal(d.cards.find(c=>c.number===274).displayName,'Polyxenus, Host of Elis');assert.equal(d.cards.find(c=>c.number===288).displayName,'Odysseus, King in Thesprotia');assert.equal(d.cards.find(c=>c.number===13).displayName,'Feign Madness');assert.equal(d.cards.find(c=>c.number===66).displayName,'Bow of Iphitus');});

test('every candidate card has a flavour-match score against a specific story element',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));assert.equal(d.cards.length,309);for(const c of d.cards){assert.ok(c.flavorStoryElement&&c.flavorStoryElement.trim(),c.id);assert.ok(Number.isInteger(c.flavorMatchScore)&&c.flavorMatchScore>=0&&c.flavorMatchScore<=5,c.id);assert.ok(c.flavorMatchRationale&&c.flavorMatchRationale.trim(),c.id)}const total=Object.values(d.flavorAudit.distribution).reduce((a,b)=>a+b,0);assert.equal(total,309);assert.equal(d.flavorAudit.cards,309);});

test('all 309 cards carry specific flavour-match scores',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));assert.equal(d.cards.length,309);for(const c of d.cards){assert.ok(typeof c.flavorStoryElement==='string'&&c.flavorStoryElement.trim(),c.id+' story element');assert.ok(Number.isInteger(c.flavorMatchScore)&&c.flavorMatchScore>=0&&c.flavorMatchScore<=5,c.id+' score');assert.ok(typeof c.flavorMatchRationale==='string'&&c.flavorMatchRationale.trim(),c.id+' rationale')}assert.equal(d.flavorAudit.cards,309);const actualDistribution=d.cards.reduce((m,c)=>(m[String(c.flavorMatchScore)]=(m[String(c.flavorMatchScore)]||0)+1,m),{});for(const score of ['0','1','2','3','4','5'])assert.equal(d.flavorAudit.distribution[score]||0,actualDistribution[score]||0,'distribution '+score);const actualAverage=d.cards.reduce((sum,c)=>sum+c.flavorMatchScore,0)/d.cards.length;assert.equal(d.flavorAudit.average,Number(actualAverage.toFixed(2)));});

test('all 309 candidate cards have specific flavour scores',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));assert.equal(d.cards.length,309);for(const c of d.cards){assert.ok(c.flavorStoryElement&&c.flavorStoryElement.trim(),c.id+' story element');assert.ok(Number.isInteger(c.flavorMatchScore),c.id+' score');assert.ok(c.flavorMatchScore>=0&&c.flavorMatchScore<=5,c.id+' score range');assert.ok(c.flavorMatchRationale&&c.flavorMatchRationale.trim(),c.id+' rationale')}const total=Object.values(d.flavorAudit.distribution).reduce((a,b)=>a+b,0);assert.equal(total,309);assert.equal(d.flavorAudit.lowMatchCards.length,d.cards.filter(c=>c.flavorMatchScore<=2).length);});

test('flavour redesign eliminates weak story matches',()=>{const fs=require('node:fs'),path=require('node:path');const d=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/data/odyssey-analysis-candidate-v1.json'),'utf8'));assert.equal(d.cards.length,309);assert.equal(d.cards.filter(c=>c.flavorMatchScore<=2).length,0);assert.equal(d.flavorAudit.lowMatchCards.length,0);assert.ok(d.flavorAudit.average>=3.9);assert.equal(d.flavorAudit.redesignedCards.length,34);assert.equal(d.cards.find(c=>c.number===30).displayName,'First Arrow at the Feast');assert.equal(d.cards.find(c=>c.number===58).displayName,'Anticleia, Shade of Home');assert.equal(d.cards.find(c=>c.number===126).displayName,'Blood-Drinking Shade');assert.equal(d.cards.find(c=>c.number===300).displayName,'Artemis, Huntress at Aulis');assert.equal(d.cards.find(c=>c.number===300).flavorMatchScore,5);});


test('Studio review notes are separate, timestamped site records',()=>{
 const notes=require('../public/mtgtools/odyssey/review-notes.js');
 assert.equal(notes.API,'/mtgtools/odyssey/api/review-notes');
 const entry=notes.appendEntry('2026-09-20T00:00:00.000Z — Earlier note','Try the alternate art','Artwork ART-123: Test Piece',new Date('2026-09-21T10:00:00.000Z'));
 assert.match(entry,/Earlier note/);assert.match(entry,/2026-09-21T10:00:00\.000Z/);assert.match(entry,/Artwork ART-123: Test Piece — Try the alternate art/);
});
test('Studio loads site-backed notes and large media previews without Sheet OAuth',()=>{
 const fs=require('node:fs'),path=require('node:path');
 const app=fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/app.html'),'utf8');
 const notes=fs.readFileSync(path.join(__dirname,'..','public/mtgtools/odyssey/review-notes.js'),'utf8');
 assert.match(app,/review-notes\.js\?v=20260921-7/);assert.match(app,/media-preview\.js/);
 assert.match(notes,/api\/review-notes/);assert.match(notes,/data-note-add-current/);assert.match(notes,/Saved ✓ This note is now in the shared Odyssey queue/);assert.doesNotMatch(notes,/OdysseySheetEditor|sheets\.googleapis|Studio Notes.*AK|Pair device|X-Odyssey-Notes-Key/);
});
test('large preview can resolve Scryfall-backed reference records',()=>{
 const media=require('../public/mtgtools/odyssey/media-preview.js');
 global.ODYSSEY_CARD_REFERENCES={cards:{x:{references:[{card:{id:'sf-test',name:'Test Reference',images:{large:'https://example.test/card.jpg'}}}]}}};
 assert.equal(media.findReference('sf-test').name,'Test Reference');
 delete global.ODYSSEY_CARD_REFERENCES;
});

test('site-backed review notes persist without Google OAuth, keys or pairing',async()=>{
 const {handleSync,OdysseyArtWorkspace}=await import('../src/odyssey-sync.mjs');
 const map=new Map(),env={ODYSSEY_ART_SYNC:{idFromName:x=>x,get(id){if(!map.has(id))map.set(id,new OdysseyArtWorkspace({storage:new Storage()}));return map.get(id)}}};
 const url='https://example.com/mtgtools/odyssey/api/review-notes';
 const get=()=>handleSync(new Request(url),env);
 const post=body=>handleSync(new Request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),env);
 let r=await get();assert.equal(r.status,200);assert.deepEqual((await r.json()).notes,[]);
 r=await post({action:'append',datasetVersion:'analysis-candidate-v2',cardId:'ODY-001',number:1,name:'Card 1',text:'Tune this card',context:'Mechanics'});
 assert.equal(r.status,200);let body=await r.json();assert.equal(body.note.status,'OPEN');assert.equal(body.note.entries[0].text,'Tune this card');
 r=await get();body=await r.json();assert.equal(body.notes.length,1);assert.equal(body.notes[0].entries[0].context,'Mechanics');
 r=await post({action:'status',datasetVersion:'analysis-candidate-v2',cardId:'ODY-001',number:1,name:'Card 1',status:'RESOLVED'});assert.equal(r.status,200);assert.equal((await r.json()).note.status,'RESOLVED');
 r=await post({action:'probe'});assert.equal(r.status,200);assert.equal((await r.json()).probe,true);
 assert.equal((await handleSync(new Request(url,{method:'POST',headers:{Origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify({action:'append',datasetVersion:'analysis-candidate-v2',cardId:'ODY-001',number:1,name:'Card 1',text:'bad'})}),env)).status,403);
});
