#!/usr/bin/env python3
"""Bounded next-round research acquisition. No writes to cards or published art."""
from pathlib import Path
from urllib.parse import urljoin
import requests, json, re, io, hashlib, concurrent.futures as cf
from bs4 import BeautifulSoup
from PIL import Image, ImageDraw
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'landscape-round2';OUT.mkdir(exist_ok=True)
for p in ['images','sources']:(OUT/p).mkdir(exist_ok=True)
issues=[];records=[]
def fetch(u,binary=False):
 r=requests.get(u,timeout=(8,20),headers={'User-Agent':'OdysseyLandscapeResearch/2.0 (bounded museum-image research)'})
 r.raise_for_status()
 if len(r.content)>35000000:raise ValueError('Review response exceeds 35 MB')
 if binary:return r.content
 if 'charset' not in r.headers.get('Content-Type','').lower():r.encoding='utf-8'
 (OUT/'sources'/hashlib.sha256(u.encode()).hexdigest()).write_text(r.text)
 return r.text

def acquire_image(a,u):
 b=fetch(u,True);im=Image.open(io.BytesIO(b));im.load();w,h=im.size
 if w<300 or h<150:raise ValueError('Preview is too small')
 im=im.convert('RGB');im.thumbnail((2400,2400));file='images/'+hashlib.sha256(a['source'].encode()).hexdigest()[:16]+'.jpg';im.save(OUT/file,quality=91)
 a.update(imageUrl=u,sourceWidth=w,sourceHeight=h,width=im.width,height=im.height,imageFile=file,imageHash=hashlib.sha256(b).hexdigest(),imageDecoded=True)

def make(title,source,artist,institution,group,**kwargs):
 return dict(title=title,source=source,artist=artist,institution=institution,collection=group,date='',medium='',rights='YELLOW — image-use terms not verified',imageDecoded=False,**kwargs)

# Exact identifiers supplied by a cited catalogue, not generated by numeric enumeration.
HARVARD=[
('28324351','Acheron (Gorge of Suli)','pga_ms_typ_55_26_740','5 May 1849','ART-728'),
('28324352','Acheron (Suli)','pga_ms_typ_55_26_741','5 May 1849','ART-729'),
('43342614','Suli','pga_typ_dr_805_l513_49s','5 May 1849',''),
('43342613','Suli','pga_typ_dr_805_l513_49u_sz2','5 May 1849',''),
('28324353','Suli','pga_ms_typ_55_26_744','6 May 1849',''),
('28324355','Suli','pga_ms_typ_55_26_745','6 May 1849',''),
('28324354','Suli','pga_ms_typ_55_26_746','6 May 1849',''),
('28324356','Suli','pga_ms_typ_55_26_747','6 May 1849',''),
('28324357','Fanari','pga_ms_typ_55_26_748','6 May 1849',''),
('28324358','Parga','pga_ms_typ_55_26_749','7 May 1849',''),
('28324361','Parga','pga_ms_typ_55_26_750','7 May 1849',''),
('28324360','Parga','pga_ms_typ_55_26_751','7 May 1849',''),
('45372671','Parga','pga_ms_typ_55_26_752','7 May 1849',''),
('28324362','Margariti','pga_ms_typ_55_26_753','8 May 1849',''),
('28324363','Paramythia','pga_ms_typ_55_26_754','8 May 1849',''),
('28324364','Paramythia','pga_ms_typ_55_26_755','8 May 1849',''),
('28324365','Paramythia','pga_ms_typ_55_26_756','9 May 1849',''),
('28324366','Trametzus','pga_ms_typ_55_26_757','9 May 1849',''),
('28324367','Trametzus','pga_ms_typ_55_26_758','10 May 1849',''),
('28324347','Lago Zero','pga_ms_typ_55_26_736','4 May 1849',''),
('28324348','Lago Zero','','4 May 1849',''),
('28324341','Plain of Arta','pga_ms_typ_55_26_730','3 May 1849',''),
('28324312','Olympus from Nomi','pga_ms_typ_55_26_535_776','16–17 May 1849',''),
('28324317','Olympus','pga_ms_typ_55_26_535_784','20 May 1849',''),
('28324318','Olympus','pga_ms_typ_55_26_535_785','21 May 1849',''),
('28324379','Olympus','pga_ms_typ_55_26_786','21 May 1849',''),
('28324385','Olympus and plain of Pharsala','pga_ms_typ_55_26_792','22 May 1849',''),
('42802294','Baba (Tempe)','pga_ms_typ_55_26_778','18 May 1849',''),
('43272064','Tempe','pga_ms_typ_55_26_780','19 May 1849',''),
('28324315','Tempe','pga_ms_typ_55_26_535_781','19 May 1849',''),
('28324316','Tempe','pga_ms_typ_55_26_535_782','19 May 1849',''),
('28324380','Mount Ossa','pga_ms_typ_55_26_787','21 May 1849','')]
secondary='https://edwardlearandthepeloponnese.weebly.com/drawings-in-detail.html'
try:fetch(secondary)
except Exception as e:issues.append({'source':secondary,'error':str(e)})

def harvard(row):
 iid,title,obj,dt,eid=row
 a=make(title,'https://iiif.lib.harvard.edu/manifests/ids:'+iid,'Edward Lear','Houghton Library, Harvard University','Harvard — Lear Greek landscapes',objectId=obj,existingId=eid,metadataSource=secondary)
 a.update(date=dt,medium='Landscape drawing; precise medium unverified',metadataStatus='Title, date and accession from independent catalogue; primary image identifier verified when decoded')
 try:
  # Access the image service directly; the old presentation viewer may be unavailable.
  info=json.loads(fetch('https://ids.lib.harvard.edu/ids/iiif/'+iid+'/info.json'))
  base=info.get('@id') or info.get('id') or ('https://ids.lib.harvard.edu/ids/iiif/'+iid)
  acquire_image(a,base.rstrip('/')+'/full/!2400,2400/0/default.jpg')
  a['imageServiceInfo']=info
 except Exception as e:a['error']=str(e)
 return a
# Probe two existing gaps first; don't repeat dozens of requests if the service itself is unavailable.
probe=[harvard(x) for x in HARVARD[:2]];records.extend(probe)
if any(a['imageDecoded'] for a in probe):
 with cf.ThreadPoolExecutor(max_workers=4) as p:records.extend(p.map(harvard,HARVARD[2:]))
else:issues.append({'collection':'Harvard — Lear Greek landscapes','blockedRemaining':len(HARVARD)-2,'reason':'Both primary image-service probes failed; remaining calls not attempted.'})

# Primary museum catalogue and exact object-image link for the previously image-less Canea.
u='https://emuseum.toledomuseum.org/objects/49104/canea-crete'
a=make('Canea, Crete',u,'Edward Lear','Toledo Museum of Art','Lear — original drawings',objectId='1958.34',existingId='ART-726',metadataSource=u)
a.update(date='1864',medium='Watercolor, graphite, pen and brown ink, and gouache on cream paper')
try:
 d=BeautifulSoup(fetch(u),'html.parser');urls=[]
 for el in d.select('a[href],img[src],meta[property="og:image"]'):
  h=el.get('href') or el.get('src') or el.get('content') or ''
  if any(x in h for x in ['1958_34','/media/','/internal/media/']):urls.append(urljoin(u,h))
 for im in list(dict.fromkeys(urls))[:4]:
  try:acquire_image(a,im);break
  except Exception as e:a['error']=str(e)
except Exception as e:a['error']=str(e)
records.append(a)

# Source-grounded landscape plates with strong Homeric geographical relevance.
# The official Met record verifies the Scilla plate; the historical book scan supplies its image.
u='https://www.nonsenselit.org/Lear/scilla.html'
a=make('Scilla, Calabria','https://www.metmuseum.org/art/collection/search/769420','Edward Lear','The Metropolitan Museum of Art / historical book scan','Lear — Southern Calabria',objectId='66.541.49(7)',metadataSource='https://www.metmuseum.org/art/collection/search/769420',imageSourcePage=u)
a.update(date='1852',medium='Lithograph on chine collé (museum impression); published plate scan')
try:
 d=BeautifulSoup(fetch(u),'html.parser')
 for im in d.select('img[src]'):
  try:acquire_image(a,urljoin(u,im['src']));break
  except Exception as e:a['error']=str(e)
except Exception as e:a['error']=str(e)
records.append(a)

# Reuse original catalogue pages already approved as discovery sources. Their fulltext carries metadata.
met_ids=[]
for q in ['Edward Lear','William Stanley Haseltine']:
 try:
  u='https://collectionapi.metmuseum.org/public/collection/v1/search?artistOrCulture=true&hasImages=true&q='+requests.utils.quote(q)
  j=json.loads(fetch(u));met_ids.extend(j.get('objectIDs') or [])
 except Exception as e:issues.append({'source':'Met artist query '+q,'error':str(e)})
existing_sources=set()
for name in ['landscape-import.20260929.json','odyssey-data.json']:
 p=ROOT/'public/mtgtools/odyssey/data'/name
 if p.exists():
  existing_sources.update(str(a.get('source','')).replace('/en/art/','/art/') for a in json.loads(p.read_text()).get('artworks',[]))
geo=re.compile(r'Corfu|Ithaca|Olympus|Parnass|Delphi|Sparta|Tayget|Greece|Greek|Crete|Canea|Sounion|Sunium|Cape Colonna|Sorrento|Scilla|Messina|Sicil|Etna|Stromboli|Lipari|Circe|Avern|Cumae|Gaeta|Gozo|Malta|Navarino|Pylos|Delos|Acheron|Souli|\bSuli\b|Troad|Troy|Nile|Luxor|Sidon|Paphos|Gibraltar',re.I)
def met(oid):
 try:
  u='https://collectionapi.metmuseum.org/public/collection/v1/objects/'+str(oid);j=json.loads(fetch(u))
  if not geo.search(j.get('title','')) or not j.get('primaryImage'):return None
  source=j.get('objectURL') or 'https://www.metmuseum.org/art/collection/search/'+str(oid)
  if source.replace('/en/art/','/art/') in existing_sources:return None
  a=make(j['title'],source,j.get('artistDisplayName',''), 'The Metropolitan Museum of Art','Museum Greek and Mediterranean landscapes',objectId=j.get('accessionNumber',''),metadataSource=u)
  a.update(date=j.get('objectDate',''),medium=j.get('medium',''),rights='GREEN — Met Public Domain / Open Access' if j.get('isPublicDomain') else 'YELLOW — supplied image rights need verification')
  acquire_image(a,j['primaryImage']);return a
 except Exception as e:issues.append({'object':oid,'error':str(e)});return None
with cf.ThreadPoolExecutor(max_workers=4) as p:
 records.extend(a for a in p.map(met,list(dict.fromkeys(met_ids))[:180]) if a)
# Save failures as audit only; they must not inflate the next round's imported-image count.
for n,a in enumerate(records,1):a['reviewId']='R2-'+str(n).zfill(3)
(OUT/'records.json').write_text(json.dumps(records,ensure_ascii=False,indent=2))
(OUT/'issues.json').write_text(json.dumps(issues,ensure_ascii=False,indent=2))
summary={'records':len(records),'decoded':sum(a['imageDecoded'] for a in records),'metObjectsExamined':min(len(set(met_ids)),180),'cardsChanged':0}
(OUT/'summary.json').write_text(json.dumps(summary,indent=2))
for page in range((len(records)+11)//12):
 grid=Image.new('RGB',(1600,1080),'white');dr=ImageDraw.Draw(grid)
 for k,a in enumerate(records[page*12:page*12+12]):
  x=k%3*533;y=k//3*270
  if a.get('imageFile'):
   im=Image.open(OUT/a['imageFile']);im.thumbnail((510,220));grid.paste(im,(x+(510-im.width)//2,y))
  dr.text((x+6,y+225),a['reviewId']+' '+a['title'][:61],fill='black')
  dr.text((x+6,y+241),a['artist'][:35]+' | '+str(a.get('width',0))+' x '+str(a.get('height',0)),fill='black')
 grid.save(OUT/('contact-%02d.jpg'%(page+1)),quality=92)
print(json.dumps(summary,indent=2))
