#!/usr/bin/env python3
"""Build an isolated, reviewable playtest candidate. Never writes production data."""
from pathlib import Path
import copy,json,collections,re,hashlib,math
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'docs/odyssey-design-round-20260922'
base=json.loads((ROOT/'public/mtgtools/odyssey/data/odyssey-data.json').read_text()); cards=copy.deepcopy(base['cards']); bynum={c['number']:c for c in cards}
refs=json.loads((ROOT/'public/mtgtools/odyssey/data/card-references.json').read_text())['cards']
changes=[]
def change(n,why,question,refs_new=(),**fields):
 c=bynum[n]; before=copy.deepcopy(c)
 if 'name' in fields: fields.setdefault('displayName',fields['name'])
 if 'name' in fields or ('type' in fields and fields['type']!=c['type']): fields.setdefault('artReviewRequired',True)
 c.update(fields)
 if 'mana' in fields:c['mv']=sum(int(x) if x.isdigit() else 1 for x in re.findall(r'\{([^}]+)\}',c['mana']))
 c['functionalWords']=len(c['rules'].split())
 changes.append({'id':c['id'],'slot':n,'reason':why,'playtestQuestion':question,'before':before,'after':copy.deepcopy(c),'changedFields':{k:{'before':before.get(k),'after':v} for k,v in c.items() if before.get(k)!=v},'existingReferenceFacts':refs[c['id']]['references'],'newReferencesToVerify':list(refs_new),'referenceStatus':'Current-design references preserved as baseline evidence; updated candidate comparisons are provisional.'})
def omen(n,name,mana,effect,book,why,question,reference):
 c=bynum[n]; color=c['color']
 change(n,why,question,[reference],name=name,mana=mana,type='Enchantment',pt='',layout='standard',mechanics='Flash; Omen; enchantment; scry',rules=f'Flash\nWhen this enchantment enters, {effect}\n{{2}}{{{color}}}, Sacrifice this enchantment: Scry 2.',cycleIds=c['cycleIds']+['cycle.odyssey-omens'],storySourceBand=book)
omen(49,'Omen of Clear-Sky Thunder','{1}{W}',"tap up to one target creature an opponent controls. You gain 2 life.",'Odyssey Book XX','Keep the attested sign while supplying a reusable enchantment resource.','Does white need a stun counter, or does flash plus life already buy enough time?','Omen of the Sun')
omen(116,'Omen of the Dreaming Queen','{2}{U}','scry 1, then manifest fate.','Odyssey Book XIX','Preserve the dream and add an enchantment at a more conservative rate.','Does flash manifestation create excessive combat blowouts at common?','Omen of the Sea')
omen(127,'Omen of the Veiled Hall','{2}{B}','up to one target creature gets -2/-2 until end of turn.','Odyssey Book XX','Replace generic household debt with Theoclymenus seeing the suitors wrapped in darkness.','Is the removal rate fair when blink and Constellation also reward this permanent?','Omen of the Dead')
omen(135,'Omen of the Bellowing Meat','{1}{R}','it deals 2 damage to target creature.','Odyssey Book XII','Show the slaughtered cattle continuing to give signs of life; preserve cheap red interaction.','Does this overlap Shipyard Sparks too closely despite the different enchantment support?','Omen of the Forge')
omen(139,'Omen of the Hunting Hawk','{1}{G}','create a Food token and put a +1/+1 counter on up to one target creature you control.','Odyssey Book XV','The hawk with a dove is an interpreted sign; provision preserves the replaced Food role.','Does Food plus a counter make this the automatic best Omen in every green deck?','Omen of the Hunt')
change(103,'A ritual worker supplies a needed cheap white body while preserving libation flavour.','Does this do enough without crowding out the ordinary white two-drops?',name='Libation Attendant',mana='{W}',type='Creature — Human Cleric',pt='1/2',rules='When this creature enters, you gain 2 life.',mechanics='Life; ritual; crew support')
change(108,'Put wine service on a body so hospitality also supports crewing.','Is a two-mana 2/1 plus Food too efficient beside the other white commons?',name='Household Cupbearer',mana='{1}{W}',type='Creature — Human Citizen',pt='2/1',rules='When this creature enters, create a Food token.',mechanics='Food; crew support')
change(115,'Blue needs a common body which performs practical navigation.','Does this creature make the Vehicle condition useful often enough?',name='Depth-Sounding Sailor',mana='{2}{U}',type='Creature — Human Sailor',pt='2/3',rules='When this creature enters, scry 1. Then if you control a Vehicle, you may draw a card. If you do, discard a card.',mechanics='Scry; Vehicle; loot')
change(80,'Give the anonymous palace intruder an actual hidden companion rather than only generic surveillance.','Is four mana enough of a cost for two bodies and future face-up value?',mana='{3}{B}',pt='2/2',rules='When this creature enters, manifest fate.',mechanics='Manifest Fate; disguise')
change(88,'Make lotus-induced delay buy an uncertain future; keep the temptation visible.','Does the delayed 3/3 plus immediate 2/2 make a meaningful choice rather than an automatic option?',mana='{3}{G}',pt='3/3',rules='When this creature enters, you may tap it and put a stun counter on it. If you do, manifest fate.',mechanics='Manifest Fate; stun; temptation')
change(87,'A sailor reading signs is a common bridge to enchantment play.','Are five Omens and two enchantment creatures enough for a small Constellation reward?',rules='When this creature enters, scry 1.\nConstellation — Whenever an enchantment you control enters, this creature gets +1/+0 until end of turn.',mechanics='Scry; Constellation')
change(125,'The swine are people held in Circe\'s ongoing enchantment.','Does the enchantment type provide useful glue without making graveyard recursion too reliable?',type='Enchantment Creature — Boar',rules='When this creature dies, mill two cards, then you may return another enchantment card from your graveyard to your hand.',mechanics='Enchantment creature; mill; enchantment recovery')
change(112,'The existing ship-conditioned creature can also introduce Foretell at common.','Is the foretell discount useful without accelerating the four-power body too far?',rules='When this creature enters, if you control a Vehicle, scry 2.\nForetell {2}{U}',mechanics='Scry; Vehicle; Foretell')
change(123,'Choose a visibly supernatural memory of the household instead of calling an ordinary mourner an enchantment.','Can a modest escaping body support graveyard departures without exhausting limited graveyards?',name='Shade of the Waiting House',mana='{2}{B}',type='Enchantment Creature — Spirit',pt='2/2',rules='When this creature enters, mill two cards.\nEscape—{4}{B}, Exile three other cards from your graveyard.',mechanics='Enchantment creature; mill; Escape',storySourceBand='Odyssey Book XXIV / explicit fantasy extension',flavorStoryElement='A household memory persists among the shades; bodily escape is a fantasy extension, not a literal Homeric event.')
change(142,'A narrow common return enables the set\'s existing homecoming rewards.','Do cheap enter-the-battlefield effects make repeated small returns too strong?',rules='Mill two cards. You may return a creature card with mana value 2 or less from your graveyard to the battlefield tapped.',mechanics='Mill; small reanimation')
change(31,'Test reciprocal hospitality where the flavour already fits.','Is the promised Food a real opponent benefit rather than an automatic upgrade?',rules='Gift a Food\nCreate a Food token. Up to one target creature you control gets +2/+2 until end of turn. If the gift was promised, put a +1/+1 counter on that creature.',mechanics='Gift a Food; Food; growth')
change(74,'Offer a second low-complexity Gift decision across the welcome package.','Does the free Food given away outweigh four life often enough to make the choice interesting?',rules='Gift a Food\nCreate a Food token. Put a +1/+1 counter on up to one target creature that entered under your control this turn. If the gift was promised, you gain 4 life.',mechanics='Gift a Food; Food; arrival')
change(44,'Preserve the crew\'s tapped state through Survival and restore them afterward.','Does losing an immediate untap trick leave too little common defensive interaction?',rules='Up to two target creatures each get +1/+0 until end of turn. Untap those creatures at the beginning of the next end step.',mechanics='Team combat; delayed untap')
change(64,'Let the common ship demonstrate labour first and recovery afterward.','Is delayed recovery enough to keep this Vehicle attractive?',rules='Whenever this Vehicle attacks, choose up to one target creature that crewed it this turn. Untap that creature at the beginning of the next end step.\nCrew 2',mechanics='Crew; delayed untap')
change(23,'Apply the open note to the whole company preparing the attack.','Does tapping two blockers plus a team boost at three mana end common games too abruptly?',rules='Tap up to two target creatures. Creatures you control get +1/+1 until end of turn.',mechanics='Team combat; tap')
change(37,'Show a group clearing many bodies, with an inefficient body as requested.','Does removing all creature cards suppress Escape too severely?',name='Condemned Maidservants',mana='{3}{B}',pt='2/3',rules='When this creature enters, exile any number of target creature cards from a single graveyard. If one or more cards were exiled this way, you gain 2 life.',mechanics='Graveyard clearing; life',flavorStoryElement='The condemned group carries out the slain suitors and cleans the hall before its own execution; Homer names twelve women, not six.')
change(8,'Interpret the activated-ability note as a fuller enforced truce; avoid feeding guests in order to exile them.','Does shutting off abilities create too much text or too strong an answer at common?',rules="Enchant creature an opponent controls\nWhen this Aura enters, create a Food token.\nEnchanted creature can't attack or block, and its activated abilities can't be activated.",mechanics='Aura; Food; restraint')
change(110,'Let the common welcome reward the supported revelation action too.','Can players distinguish turning face up from entering without extra bookkeeping?',rules='Whenever another creature you control enters from exile or your graveyard or is turned face up, this creature gets +1/+1 until end of turn.',mechanics='Return; face-up recognition')
change(36,'Fulfil the open Basin note using separate recognition events.','Can the broad face-up trigger safely share a single once-per-turn limit?',rules="When this artifact enters, scry 2.\nWhenever a creature you control is turned face up or a legendary creature you control enters from exile or your graveyard, draw a card. This ability triggers only once each turn.",mechanics='Scry; face-up recognition; return')
change(15,'Apply Hunter’s explicit sacrifice version: a nontoken creature is lost before the campaign can advance. Retain the existing UB identity and mass-tap role.','Is four mana plus a nontoken creature a meaningful cost for a multiplayer attack opening and two cards? Test death/recursion engines and counterspell exposure.',['Sleep',"Altar's Reap"],name="Iphigenia's Sacrifice",mana='{2}{U}{B}',color='UB',frame='UB',type='Sorcery',rules='As an additional cost to cast this spell, sacrifice a nontoken creature.\nTap all creatures your opponents control. Draw two cards.',mechanics='Creature sacrifice; mass tap; card draw',storySourceBand='Aeschylus, Agamemnon / actual sacrifice at Aulis',flavorStoryElement='Agamemnon has Iphigenia killed so the fleet can proceed to war. Her loss buys passage for the expedition; she is not rescued or replaced.',flavorMatchScore=4,flavorMatchRationale='Mandatory sacrifice precedes the advance; tapping clears a combat route and drawing replenishes the expedition. These benefits are game abstractions. The generic victim and absence of the family’s later vengeance leave some specificity unrepresented.')
change(174,'Make the rare Penelope perform unweaving in the existing main-set slot.','Does one removed lore counter per turn hold a powerful final chapter indefinitely too easily?',['Satsuki, the Living Lore','Power Conduit','Scholar of New Horizons'],mana='{1}{W}{U}',color='WU',frame='WU',pt='2/4',rules='Whenever an enchantment you control enters, you may remove a lore counter from target Saga you control. This ability triggers only once each turn.\n{2}{W}{U}, {T}: Return target enchantment card from your graveyard to your hand.',mechanics='Saga unweaving; enchantment recovery',flavorStoryElement='Penelope weaves the promised shroud by day and undoes the work by night, postponing the conclusion demanded by the suitors.')
change(238,'Use ordinary event templates and include noncreatures without describing a vague return event.','Does one card per turn still make cheap flash Omens and blink too strong?',rules="Whenever a permanent you control enters from exile or is turned face up, draw a card. This ability triggers only once each turn.\n{2}{W}{U}: Exile another target nonland permanent you control, then return it to the battlefield under its owner's control. Activate only as a sorcery.")
change(221,'Remove an undefined damage source while preserving the cattle Saga\'s punishment.','Can players track Foods sacrificed during this Saga\'s presence without excessive memory?',rules=bynum[221]['rules'].replace('Helios deals 3 damage to you','this Saga deals 3 damage to you'))
for n in [17,93,166,280,282]:
 c=bynum[n];name=c['name'];rules=c['rules'].replace('the controller of '+name+' sacrifices that Aura','sacrifice this Aura').replace('When you sacrifice '+name,'When you sacrifice this Aura')
 # Preserve the expressly requested granted Survival ability and its controller semantics.
 # A self-reference inside the creature's granted ability cannot safely call the source Aura "this Aura".
 rules=c['rules'].replace('When you sacrifice '+name,'When you sacrifice this Aura')
 change(n,'Use this Aura in the Aura\'s own reward ability; retain the necessary named source inside the granted creature ability.','Does the shorter reward remain readable while the granted Survival ability preserves its original multiplayer behaviour?',rules=rules)
change(7,'Make the foot-washing recognition scene a second common direct-return enabler; blink also reveals a manifested permanent.','Does two mana and tapped return sufficiently constrain repeated ETB value? Compare lost untap combat utility.',['Cloudshift','Ephemerate'],mana='{1}{W}',rules="Exile target creature you control, then return that card to the battlefield tapped under its owner's control. You gain 2 life.",mechanics='Blink; recognition; life',flavorStoryElement='Eurycleia washes the disguised Odysseus and recognises his scar. The familiar person becomes visible through care.',flavorMatchScore=4,flavorMatchRationale='Blink removes the face-down presentation of a manifested permanent and renews entry effects; tapped return conveys rest. Disappearance is a gameplay abstraction, not a literal feature of the scene. A manifested instant or sorcery cannot return to the battlefield.',storySourceBand='Odyssey Book XIX / Eurycleia recognises the scar')
change(51,'Connect counsel and identity to the supported face-up action while limiting repeated untap engines.','Can players order recognition and Survival triggers correctly, and does one untap per turn offer enough reward?',rules='Whenever one or more cards are exiled from your library for the first time each turn, tap up to one target creature an opponent controls.\nWhenever a permanent you control enters from exile or is turned face up, untap up to one target creature you control. This ability triggers only once each turn.',mechanics='Library exile; face-up recognition; limited untap',flavorStoryElement='Mentor defends the household; Athena takes his form and helps Telemachus prepare and depart.',flavorMatchScore=4,flavorMatchRationale='Concealment opens a way through opposition; recognition readies an ally. The tap/untap model abstracts coordinated assistance, not a literal restoration of the dead. Distinguish human Mentor from Athena in his likeness.')
change(90,'Make Nausicaa welcome both the returning traveller and the newly revealed person. Preserve her Adventure.','Does the two-mana body plus counter reward compete fairly with the other signposts? The Adventure alone still does not trigger this ability.',rules="Whenever a permanent you control enters from exile or is turned face up, untap it. If it's a creature, put a +1/+1 counter on it. This ability triggers only once each turn.\n//Adventure// Find the Castaway — {1}{U} — Sorcery — Adventure\nManifest fate.",mechanics='Adventure; Manifest Fate; face-up recognition; counters',flavorStoryElement='Nausicaa stands her ground, supplies the castaway, and sees his transformed appearance after washing and clothing.',flavorMatchScore=4,flavorMatchRationale='Her Adventure discovers the unknown traveller; later revelation or return lets her restore and strengthen them. The new event explicitly supports face-up play. Generic exile still stands for welcome rather than a literal journey from another realm.')
change(56,'Replace benevolent rescue with consumption of household resources for personal growth and pressure.','Is a 3/3 that can grow once at each of your end steps too efficient with recurring Food? Check death triggers, copied triggers and extra end steps.',['Ravenous Squirrel'],rules='At the beginning of your end step, you may sacrifice another creature or a Food. If you do, put a +1/+1 counter on Antinous and each opponent loses 1 life.',mechanics='End-step sacrifice; Food; growth; opponent life loss',flavorStoryElement='Antinous consumes the absent king’s household resources, pressures the heir and refuses generosity to the disguised stranger.',flavorMatchScore=4,flavorMatchRationale='The player gives up household bodies or provisions; Antinous alone grows while rivals lose life. Sacrificing your own resources is an abstraction of his control within the occupied household, not literal theft from the opposing player. The card supplies no rescue or replacement body.')
change(213,'Replace repeated disappearance with a bond to the household ground and a reward for reunion.','Is three mana too efficient for a protected draw engine in legend-dense Commander decks? Test chosen-land tracking, removal windows and the two-creature threshold.',['Flowering of the White Tree','Tome of Legends'],rules='As this artifact enters, choose a land you control.\nAs long as you control the chosen land, this artifact has hexproof and legendary creatures you control have ward {1}.\nAt the beginning of your end step, if you control the chosen land and two or more legendary creatures, draw a card.',mechanics='Chosen land; hexproof; legendary ward; reunion draw',storySourceBand='Odyssey Book XXIII / the rooted bed and recognition test',flavorStoryElement='Odysseus built the marriage bed around an olive trunk. Penelope tests his identity by ordering it moved; his knowledge of its construction proves their shared history.',flavorMatchScore=4,flavorMatchRationale='A particular land anchors the protection and reunion reward; losing that land disables them. Two legendary creatures stand for the reunited couple. Hexproof and card draw are gameplay abstractions; the design does not prohibit all movement or require the specific spouses.')
change(235,'Give the opened bag an actual cost in enduring progress, and depict its contents as wind rather than real treasure.','Does the delayed land loss make this unattractive without counter manipulation, or too efficient when chapter III is avoided? Test Penelope and other ways to repeat chapter II.',['Reckless Impulse','Seething Song'],rules='I — Exile the top two cards of your library. Until the end of your next turn, you may play those cards.\nII — Add {R}{R}{R}.\nIII — Sacrifice a land.',mechanics='Saga; impulse access; ritual mana; land sacrifice',storySourceBand='Odyssey Book X / Aeolus and the opened bag',flavorStoryElement='Within sight of home, the crew mistakes Aeolus’s bag of winds for hidden wealth. Opening it releases a storm that drives the ships back to Aeolus, who refuses further help.',flavorMatchScore=4,flavorMatchRationale='Temporary access tempts the player, a mana burst represents released force, and land sacrifice removes durable progress. These are game abstractions: the crew finds no actual treasure and no literal island is destroyed. Counter manipulation can postpone the price, so catastrophe is not guaranteed by this text.')
def metrics(cs):
 common=[c for c in cs if c['rarity']=='C'];nonland=[c for c in common if 'Land' not in c['type']]
 return {'cards':len(cs),'rarity':dict(collections.Counter(c['rarity'] for c in cs)),'lands':sum('Land' in c['type'] for c in cs),'doubleFaced':sum(c['layout']=='transform' for c in cs),'commonCreatures':sum('Creature' in c['type'] for c in nonland),'commonEnchantmentCreatures':sum('Enchantment Creature' in c['type'] for c in nonland),'commonEnchantments':sum('Enchantment' in c['type'] for c in nonland),'commonFoodSources':sum('create a food token' in c['rules'].lower() or 'Artifact — Food' in c['type'] for c in nonland),'commonManifestFate':sum('manifest fate' in c['rules'].lower() for c in nonland),'commonForetell':sum('foretell' in c['rules'].lower() for c in nonland),'commonEscape':sum('escape' in c['rules'].lower() for c in nonland),'commonGift':sum('Gift a Food' in c['rules'] for c in nonland),'commonConstellation':sum('Constellation' in c['rules'] for c in nonland),'commonCreatureByColor':dict(collections.Counter(c['color'] for c in nonland if 'Creature' in c['type']))}
summary={'status':'isolated-playtest-candidate-not-live','baseDatasetVersion':base['datasetVersion'],'changedCards':len(changes),'before':metrics(base['cards']),'after':metrics(cards),'warnings':['No played matches have been performed.','Source briefs are a first pass; unresolved passage verification remains labelled.','Hunter approved WU Penelope and explicitly selected actual sacrifice for Iphigenia. Slot 015 now remains UB; its proposed rate still needs testing.','The Ordeals still grant Survival to their enchanted creatures; source names remain where self-reference would change meaning.','The seven Studio notes remain open until actual implementation is verified.','Candidate references need a production refresh before integration.']}
assert len(cards)==309 and len({c['id'] for c in cards})==309
assert summary['before']['rarity']==summary['after']['rarity'] and summary['after']['lands']==40 and summary['after']['doubleFaced']==1
protected=['id','number','rarity','primaryArt','credit','source','imageUrl','productLayer']
for old,new in zip(base['cards'],cards):
 for k in protected: assert old.get(k)==new.get(k),(old['id'],k)
for name,value in [('candidate-cards.json',{'schema':'odyssey-design-candidate/v1','summary':summary,'cards':cards}),('candidate-changes.json',changes),('candidate-summary.json',summary)]:
 (OUT/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(summary,indent=2))
