/* Native Cloudflare form delivery. No list subscription, no submitted-data storage.
 * Activate only after Email Service and Turnstile are configured. */
export const CONTACT_API='/mtgtools/odyssey/api/contact';
const roles={updates:'Follow the reveals',playtesting:'Playtest the set',contributing:'Contribute design or art research'};
const HOST='kliawota.design',CAP=12000;
const reply=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const email=s=>typeof s==='string'&&s.length<=254&&/^[A-Za-z0-9.!#$%&'*+\/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?\.[A-Za-z]{2,63}$/.test(s)&&!s.includes('..');
export function settings(env){const from=env.ODYSSEY_CONTACT_FROM||'UniverseEternal@kliawota.design',key=env.ODYSSEY_TURNSTILE_SITEKEY;return {enabled:env.ODYSSEY_CONTACT_ENABLED==='true'&&typeof env.ODYSSEY_EMAIL?.send==='function'&&email(env.ODYSSEY_CONTACT_TO)&&email(from)&&from.toLowerCase().endsWith('@'+HOST)&&typeof key==='string'&&key.length>10&&!!env.ODYSSEY_TURNSTILE_SECRET,from,sitekey:key};}
async function jsonBody(request){if(Number(request.headers.get('content-length')||0)>CAP)throw Error('too large');const reader=request.body?.getReader();if(!reader)throw Error('missing body');let n=0;const chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;n+=value.byteLength;if(n>CAP){await reader.cancel();throw Error('too large');}chunks.push(value);}const b=new Uint8Array(n);let at=0;for(const c of chunks){b.set(c,at);at+=c.byteLength;}return JSON.parse(new TextDecoder().decode(b));}
export function validate(b){if(!b||typeof b!=='object'||Array.isArray(b)||Object.keys(b).some(k=>!['name','email','role','message','consent','token','website'].includes(k)))throw Error('Invalid form.');if(!email(b.email)||!Object.hasOwn(roles,b.role)||b.consent!==true)throw Error('Enter a valid email, choose an interest and confirm contact permission.');if(typeof b.name!=='string'||b.name.length>80||/[\x00-\x1f\x7f]/.test(b.name))throw Error('Enter a name of 80 characters or fewer.');if(typeof b.message!=='string'||b.message.length>2000||/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(b.message))throw Error('The message must be 2,000 characters or fewer.');if(typeof b.token!=='string'||!b.token||b.token.length>2048||typeof b.website!=='string'||b.website)throw Error('Complete the verification and try again.');return {name:b.name.trim(),email:b.email,role:b.role,message:b.message.trim(),consent:true,token:b.token};}
export async function routeContact(request,env,fetcher=fetch){const u=new URL(request.url);if(u.pathname!==CONTACT_API)return null;if(!['GET','POST'].includes(request.method))return reply({error:'Method not allowed.'},405);const cfg=settings(env);if(request.method==='GET')return reply(cfg.enabled?{enabled:true,sitekey:cfg.sitekey}:{enabled:false});
 if(request.headers.get('origin')!==u.origin||u.hostname!==HOST)return reply({error:'Use the form on kliawota.design.'},403);
 if(!cfg.enabled)return reply({error:'Direct sending is not enabled yet. Please use the email link instead.'},503);
 if(!request.headers.get('content-type')?.startsWith('application/json'))return reply({error:'Invalid request format.'},415);
 let body;try{body=validate(await jsonBody(request));}catch(e){return reply({error:e.message==='too large'?'The message is too large.':e.message==='missing body'?'Enter your message.':e instanceof SyntaxError?'Invalid form.':e.message},400);}
 let verification;try{const data=new FormData();data.set('secret',env.ODYSSEY_TURNSTILE_SECRET);data.set('response',body.token);const ip=request.headers.get('CF-Connecting-IP');if(ip)data.set('remoteip',ip);const r=await fetcher('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:data,signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('verification unavailable');verification=await r.json();}catch(_){return reply({error:'Verification is temporarily unavailable. Your message has not been sent.'},503);}
 if(!verification.success||verification.hostname!==HOST||verification.action!=='odyssey-interest')return reply({error:'Verification expired or failed. Please verify again; your message has not been sent.'},403);
 try{await env.ODYSSEY_EMAIL.send({to:env.ODYSSEY_CONTACT_TO,from:{email:cfg.from,name:'Universes Eternal — Odyssey'},replyTo:body.email,subject:'Odyssey interest: '+roles[body.role],text:'Odyssey website interest request\n\nName: '+(body.name||'Not supplied')+'\nReply address: '+body.email+'\nInterest: '+roles[body.role]+'\n\n'+(body.message||'No additional message.')+'\n\nContact permission: explicitly confirmed on the website.\nThis is an individual request, not an automatic newsletter subscription.\nSubmitted: '+new Date().toISOString()});return reply({submitted:true,message:'Your message has been submitted to Hunter. Thank you for joining the voyage.'},202);}catch(_){return reply({error:'Sending failed. Your message is still in the form; please retry or use the email link.'},502);}
}
